// Generated by Framer (2306ade)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["ll3tvqS4r", "sVbL9SUT6"];
const serializationHash = "framer-umYXE";
const variantClassNames = {
  ll3tvqS4r: "framer-v-19xyu7p",
  sVbL9SUT6: "framer-v-1x771l6",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const transition2 = { duration: 0, type: "tween" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Hide: "ll3tvqS4r", Show: "sVbL9SUT6" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "ll3tvqS4r",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "ll3tvqS4r",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppearfv71xy = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("sVbL9SUT6"), 10);
  });
  useOnVariantChange(baseVariant, { default: onAppearfv71xy });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "sVbL9SUT6") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "sVbL9SUT6") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          { sVbL9SUT6: { value: transition2 } },
          baseVariant,
          gestureVariant
        ),
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-19xyu7p",
            className,
            classNames
          ),
          "data-framer-name": "Hide",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "ll3tvqS4r",
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 17,
            borderBottomRightRadius: 17,
            borderTopLeftRadius: 17,
            borderTopRightRadius: 17,
            ...style,
          },
          ...addPropertyOverrides(
            { sVbL9SUT6: { "data-framer-name": "Show" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1cl09u1",
            "data-framer-name": "Image Wrap",
            layoutDependency: layoutDependency,
            layoutId: "OjReNUsoZ",
            children: [
              isDisplayed() &&
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 7200,
                    intrinsicWidth: 5760,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0
                    ),
                    pixelHeight: 7200,
                    pixelWidth: 5760,
                    sizes: "191px",
                    src: "https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg",
                    srcSet:
                      "https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=1024 819w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=2048 1638w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=4096 3276w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg 5760w",
                  },
                  className: "framer-gwidpj",
                  "data-framer-name": "Image",
                  layoutDependency: layoutDependency,
                  layoutId: "U9ioWgEo3",
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsxs(React.Fragment, {
                    children: [
                      /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                          "--framer-font-family":
                            '"GT Flexa Mono Trial", monospace',
                          "--framer-font-size": "10px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(149, 148, 148))",
                        },
                        children: "JEAN-MICHEL BASQUIAT",
                      }),
                      /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                          "--framer-font-family":
                            '"GT Flexa Mono Trial", monospace',
                          "--framer-font-size": "10px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-2gxw0f, rgb(149, 148, 148))",
                        },
                        children: "// (1960-1988)",
                      }),
                    ],
                  }),
                  className: "framer-1sqgsvl",
                  fonts: ["GF;GT Flexa Mono Trial-regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "Ic6j6Lts0",
                  style: {
                    "--extracted-2gxw0f": "rgb(149, 148, 148)",
                    "--extracted-r6o4lv": "rgb(149, 148, 148)",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    pixelHeight: 254,
                    pixelWidth: 254,
                    src: "https://framerusercontent.com/images/hp2Y3ziuaTacwTSTvumilMPHsO8.jpg",
                  },
                  className: "framer-pj3b3",
                  "data-border": true,
                  layoutDependency: layoutDependency,
                  layoutId: "dorMJ4bRN",
                  style: {
                    "--border-bottom-width": "0.5px",
                    "--border-color": "rgb(34, 34, 34)",
                    "--border-left-width": "0.5px",
                    "--border-right-width": "0.5px",
                    "--border-style": "solid",
                    "--border-top-width": "0.5px",
                    borderBottomLeftRadius: 4,
                    borderBottomRightRadius: 4,
                    borderTopLeftRadius: 4,
                    borderTopRightRadius: 4,
                    boxShadow: "0px 4px 20px 0px rgba(255, 56, 56, 0.2)",
                  },
                  ...addPropertyOverrides(
                    {
                      sVbL9SUT6: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) + 0 + 6
                          ),
                          pixelHeight: 254,
                          pixelWidth: 254,
                          src: "https://framerusercontent.com/images/hp2Y3ziuaTacwTSTvumilMPHsO8.jpg",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-umYXE.framer-mfohfz, .framer-umYXE .framer-mfohfz { display: block; }",
  ".framer-umYXE.framer-19xyu7p { height: 220px; overflow: hidden; position: relative; width: 178px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-umYXE .framer-1cl09u1 { bottom: 220px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
  ".framer-umYXE .framer-gwidpj { flex: none; height: 224px; left: calc(50.00000000000002% - 191px / 2); overflow: visible; position: absolute; top: 0px; width: 191px; }",
  ".framer-umYXE .framer-1sqgsvl { flex: none; height: auto; position: absolute; right: 4px; top: 15px; white-space: pre; width: auto; }",
  ".framer-umYXE .framer-pj3b3 { flex: none; height: 128px; left: 10px; position: absolute; top: 6px; width: 91px; z-index: 1; }",
  ".framer-umYXE.framer-v-1x771l6.framer-19xyu7p { height: 142px; width: 230px; }",
  ".framer-umYXE.framer-v-1x771l6 .framer-1cl09u1 { bottom: 0px; }",
  '.framer-umYXE[data-border="true"]::after, .framer-umYXE [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 220
 * @framerIntrinsicWidth 178
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"sVbL9SUT6":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerOMVjUlEAr = withCSS(Component, css, "framer-umYXE");
export default FramerOMVjUlEAr;
FramerOMVjUlEAr.displayName = "Image 4";
FramerOMVjUlEAr.defaultProps = { height: 220, width: 178 };
addPropertyControls(FramerOMVjUlEAr, {
  variant: {
    options: ["ll3tvqS4r", "sVbL9SUT6"],
    optionTitles: ["Hide", "Show"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerOMVjUlEAr, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerOMVjUlEAr",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "220",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"sVbL9SUT6":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "178",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./OMVjUlEAr.map
