// Generated by Framer (29550c4)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import X from "https://framerusercontent.com/modules/29Eu6tDVcWIZwJL1Nh4h/zpJg2oiOBazkQeZJNCYy/YW4GE5nV0.js";
const XFonts = getFonts(X);
const serializationHash = "framer-6V2ry";
const variantClassNames = { gtLLCTqkj: "framer-v-1jef8pp" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ click, height, id, width, ...props }) => {
  return { ...props, C28ffcZ1X: click ?? props.C28ffcZ1X };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, C28ffcZ1X, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "gtLLCTqkj",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapc159a1 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (C28ffcZ1X) {
      const res = await C28ffcZ1X(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1jef8pp",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "gtLLCTqkj",
          onTap: onTapc159a1,
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(X, {
            animated: true,
            className: "framer-iilmny",
            layoutDependency: layoutDependency,
            layoutId: "JgLTcHZWR",
            style: { "--43q7um": "rgb(255, 255, 255)" },
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-6V2ry.framer-ouwf3l, .framer-6V2ry .framer-ouwf3l { display: block; }",
  ".framer-6V2ry.framer-1jef8pp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-6V2ry .framer-iilmny { flex: none; height: var(--framer-aspect-ratio-supported, 32px); position: relative; width: 32px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"C28ffcZ1X":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramermEgT8xAO4 = withCSS(Component, css, "framer-6V2ry");
export default FramermEgT8xAO4;
FramermEgT8xAO4.displayName = "X";
FramermEgT8xAO4.defaultProps = { height: 32, width: 32 };
addPropertyControls(FramermEgT8xAO4, {
  C28ffcZ1X: { title: "Click", type: ControlType.EventHandler },
});
addFonts(FramermEgT8xAO4, [{ explicitInter: true, fonts: [] }, ...XFonts], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramermEgT8xAO4",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "32",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "32",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}',
        framerVariables: '{"C28ffcZ1X":"click"}',
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./mEgT8xAO4.map
