// Generated by Framer (98b71dc)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Image13 from "https://framerusercontent.com/modules/bYTr4OPupWfgKGVPkAyE/CqDacQwXL1xxW5idjugO/TIaEc5gAU.js";
const Image13Fonts = getFonts(Image13);
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
  BpTqXL4Cu: { hover: true },
  uxq8e56t3: { hover: true },
};
const cycleOrder = ["uxq8e56t3", "BpTqXL4Cu", "UaQvxF0r9"];
const serializationHash = "framer-oz65x";
const variantClassNames = {
  BpTqXL4Cu: "framer-v-1alyp99",
  UaQvxF0r9: "framer-v-kndagq",
  uxq8e56t3: "framer-v-2hlutn",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
  const [visible, setVisible] = useOverlayState({ blockDocumentScrolling });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "no hover": "UaQvxF0r9",
  "Variant 1": "uxq8e56t3",
  "Variant 2": "BpTqXL4Cu",
};
const getProps = ({ fontSize, height, id, width, ...props }) => {
  return {
    ...props,
    Ul4jJ9FzJ: fontSize ?? props.Ul4jJ9FzJ ?? 48,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "uxq8e56t3",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, Ul4jJ9FzJ, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "uxq8e56t3",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnterupml6a = ({ overlay, loadMore }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isHovered: true });
      overlay.show();
    });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "BpTqXL4Cu-hover") return true;
    return false;
  };
  const ref1 = React.useRef(null);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Overlay, {
        blockDocumentScrolling: false,
        enabled: isDisplayed(),
        children: (overlay) =>
          /*#__PURE__*/ _jsx(_Fragment, {
            children: /*#__PURE__*/ _jsx(Transition, {
              value: transition1,
              children: /*#__PURE__*/ _jsxs(motion.div, {
                ...restProps,
                ...gestureHandlers,
                className: cx(
                  scopingClassNames,
                  "framer-2hlutn",
                  className,
                  classNames
                ),
                "data-framer-name": "Variant 1",
                "data-highlight": true,
                id: `${layoutId}-2hlutn`,
                layoutDependency: layoutDependency,
                layoutId: "uxq8e56t3",
                onMouseEnter: onMouseEnterupml6a({ overlay }),
                ref: refBinding,
                style: { ...style },
                ...addPropertyOverrides(
                  {
                    "BpTqXL4Cu-hover": { "data-framer-name": undefined },
                    "uxq8e56t3-hover": { "data-framer-name": undefined },
                    BpTqXL4Cu: { "data-framer-name": "Variant 2" },
                    UaQvxF0r9: { "data-framer-name": "no hover" },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1qx171c",
                    layoutDependency: layoutDependency,
                    layoutId: "EwnqMOfNc",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "013.",
                          }),
                        }),
                        className: "framer-x4b8i0",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "oev_4Pmy3",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b": Ul4jJ9FzJ,
                        },
                        variants: {
                          "BpTqXL4Cu-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                          "uxq8e56t3-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "BpTqXL4Cu-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "013",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "uxq8e56t3-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "013",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children:
                              "TAKE YOUR WORK SERIOUSLY, YOURSELF LESS SO.",
                          }),
                        }),
                        className: "framer-tjdtzp",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "XpJcc0s2a",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b": Ul4jJ9FzJ,
                        },
                        variants: {
                          "BpTqXL4Cu-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                          "uxq8e56t3-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "BpTqXL4Cu-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "TAKE YOUR WORK SERIOUSLY, YOURSELF LESS SO",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "uxq8e56t3-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-Ul4jJ9FzJ-NmQM8ZW7b) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "TAKE YOUR WORK SERIOUSLY, YOURSELF LESS SO",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    ],
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(AnimatePresence, {
                      children:
                        overlay.visible &&
                        /*#__PURE__*/ _jsx(Floating, {
                          alignment: "center",
                          anchorRef: refBinding,
                          className: cx(scopingClassNames, classNames),
                          collisionDetection: true,
                          collisionDetectionPadding: 20,
                          "data-framer-portal-id": `${layoutId}-2hlutn`,
                          offsetX: 0,
                          offsetY: 10,
                          onDismiss: overlay.hide,
                          placement: "bottom",
                          safeArea: true,
                          zIndex: 11,
                          children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation1,
                            className: "framer-1qkn1qr",
                            exit: animation,
                            initial: animation2,
                            layoutDependency: layoutDependency,
                            layoutId: "yvZbm6wP4",
                            ref: ref1,
                            role: "dialog",
                            style: {
                              backgroundColor: "rgb(255, 255, 255)",
                              borderBottomLeftRadius: 10,
                              borderBottomRightRadius: 10,
                              borderTopLeftRadius: 10,
                              borderTopRightRadius: 10,
                              boxShadow:
                                "0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
                            },
                            variants: {
                              "BpTqXL4Cu-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                boxShadow: "none",
                              },
                            },
                            children: /*#__PURE__*/ _jsx(
                              ComponentViewportProvider,
                              {
                                width: "178px",
                                ...addPropertyOverrides(
                                  { "BpTqXL4Cu-hover": { width: "219px" } },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-k8qekz-container",
                                    "data-framer-name": "013",
                                    layoutDependency: layoutDependency,
                                    layoutId: "VfnA9VD8I-container",
                                    name: "013",
                                    nodeId: "VfnA9VD8I",
                                    rendersWithMotion: true,
                                    scopeId: "NmQM8ZW7b",
                                    children: /*#__PURE__*/ _jsx(Image13, {
                                      height: "100%",
                                      id: "VfnA9VD8I",
                                      layoutId: "VfnA9VD8I",
                                      name: "013",
                                      style: { height: "100%", width: "100%" },
                                      variant: "NUbX7uVzy",
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }
                            ),
                          }),
                        }),
                    }),
                ],
              }),
            }),
          }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-oz65x.framer-1lhit0b, .framer-oz65x .framer-1lhit0b { display: block; }",
  ".framer-oz65x.framer-2hlutn { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
  ".framer-oz65x .framer-1qx171c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-oz65x .framer-x4b8i0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-oz65x .framer-tjdtzp { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-oz65x .framer-1qkn1qr { height: 150px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-oz65x .framer-k8qekz-container { flex: none; height: 220px; left: 0px; position: absolute; top: 0px; width: 178px; }",
  ".framer-oz65x.framer-v-kndagq.framer-2hlutn { cursor: unset; }",
  ".framer-oz65x.framer-v-1alyp99.hover .framer-1qkn1qr { height: 160px; width: 260px; }",
  ".framer-oz65x.framer-v-1alyp99.hover .framer-k8qekz-container { bottom: 0px; height: unset; left: calc(50.38461538461541% - 219px / 2); width: 219px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 115
 * @framerIntrinsicWidth 1100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"BpTqXL4Cu":{"layout":["fixed","auto"]},"UaQvxF0r9":{"layout":["fixed","auto"]},"cshbX8aV_":{"layout":["fixed","auto"]},"iQahbwLko":{"layout":["fixed","auto"]}}}
 * @framerVariables {"Ul4jJ9FzJ":"fontSize"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerNmQM8ZW7b = withCSS(Component, css, "framer-oz65x");
export default FramerNmQM8ZW7b;
FramerNmQM8ZW7b.displayName = "013";
FramerNmQM8ZW7b.defaultProps = { height: 115, width: 1100 };
addPropertyControls(FramerNmQM8ZW7b, {
  variant: {
    options: ["uxq8e56t3", "BpTqXL4Cu", "UaQvxF0r9"],
    optionTitles: ["Variant 1", "Variant 2", "no hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
  Ul4jJ9FzJ: { defaultValue: 48, title: "Font Size", type: ControlType.Number },
});
addFonts(
  FramerNmQM8ZW7b,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "GT Flexa Mono Trial Md",
          source: "custom",
          uiFamilyName: "GT Flexa Mono Trial Md",
          url: "https://framerusercontent.com/assets/bytIjhUjhiCYHWtmBe4nrOXxwJM.woff2",
        },
      ],
    },
    ...Image13Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerNmQM8ZW7b",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "1100",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"BpTqXL4Cu":{"layout":["fixed","auto"]},"UaQvxF0r9":{"layout":["fixed","auto"]},"cshbX8aV_":{"layout":["fixed","auto"]},"iQahbwLko":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerIntrinsicHeight: "115",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerVariables: '{"Ul4jJ9FzJ":"fontSize"}',
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./NmQM8ZW7b.map
