// Generated by Framer (a1ad18b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = {
  ddKSdeclD: { hover: true },
  X_SXtY5JO: { hover: true },
  za7e8QsYt: { hover: true },
};
const cycleOrder = [
  "X_SXtY5JO",
  "ddKSdeclD",
  "t1xg1bIzj",
  "za7e8QsYt",
  "aAMbupUlB",
];
const serializationHash = "framer-prKbP";
const variantClassNames = {
  aAMbupUlB: "framer-v-mtlfhl",
  ddKSdeclD: "framer-v-1ksxphj",
  t1xg1bIzj: "framer-v-idoy5d",
  X_SXtY5JO: "framer-v-1tmqiip",
  za7e8QsYt: "framer-v-169avwo",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "X_SXtY5JO",
  "Variant 2": "ddKSdeclD",
  "Variant 3": "t1xg1bIzj",
  "Variant 4": "za7e8QsYt",
  "Variant 5": "aAMbupUlB",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "X_SXtY5JO",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "X_SXtY5JO",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1o2v8hv = activeVariantCallback(async (...args) => {
    setVariant("X_SXtY5JO");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["t1xg1bIzj", "aAMbupUlB"].includes(baseVariant)) return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (["t1xg1bIzj", "aAMbupUlB"].includes(baseVariant)) return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1tmqiip",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "X_SXtY5JO",
          ref: refBinding,
          style: {
            backgroundColor: "rgba(0, 0, 0, 0)",
            boxShadow: "none",
            ...style,
          },
          variants: {
            "ddKSdeclD-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow:
                "inset 0px 4px 4px 0px rgb(255, 76, 36), 0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            "X_SXtY5JO-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow:
                "inset 0px 4px 4px 0px rgb(255, 76, 36), 0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            "za7e8QsYt-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow:
                "inset 0px 4px 4px 0px rgb(255, 76, 36), 0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            aAMbupUlB: {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
              boxShadow: "0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
          },
          ...addPropertyOverrides(
            {
              "ddKSdeclD-hover": { "data-framer-name": undefined },
              "X_SXtY5JO-hover": { "data-framer-name": undefined },
              "za7e8QsYt-hover": { "data-framer-name": undefined },
              aAMbupUlB: { "data-framer-name": "Variant 5" },
              ddKSdeclD: { "data-framer-name": "Variant 2" },
              t1xg1bIzj: { "data-framer-name": "Variant 3" },
              za7e8QsYt: { "data-framer-name": "Variant 4" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-amat49",
              layoutDependency: layoutDependency,
              layoutId: "OgBTKTrDn",
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1cy3dko",
                layoutDependency: layoutDependency,
                layoutId: "YT1XRRODE",
                children: [
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-16a4ulo",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "B6DzxRILU",
                      transformTemplate: transformTemplate1,
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h3, {
                            dir: "auto",
                            style: {
                              "--font-selector":
                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                              "--framer-font-family":
                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                              "--framer-font-size": "88px",
                              "--framer-letter-spacing": "-4px",
                              "--framer-line-height": "76px",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-a0htzi, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                            },
                            children: "Two Weeks",
                          }),
                        }),
                        className: "framer-18zpv0k",
                        "data-framer-name": "Step Title",
                        fonts: ["GF;Suisse Int'l-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "SF12dpVFc",
                        style: {
                          "--extracted-a0htzi":
                            "var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61))",
                          "--framer-paragraph-spacing": "0px",
                        },
                        variants: {
                          "ddKSdeclD-hover": {
                            "--extracted-a0htzi":
                              "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                          },
                          "X_SXtY5JO-hover": {
                            "--extracted-a0htzi":
                              "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                          },
                          "za7e8QsYt-hover": {
                            "--extracted-a0htzi":
                              "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                          },
                        },
                        verticalAlignment: "center",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "ddKSdeclD-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h3, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "88px",
                                    "--framer-letter-spacing": "-4px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                  },
                                  children: "Two Weeks",
                                }),
                              }),
                            },
                            "X_SXtY5JO-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h3, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "88px",
                                    "--framer-letter-spacing": "-4px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                  },
                                  children: "Two Weeks",
                                }),
                              }),
                            },
                            "za7e8QsYt-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h3, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "88px",
                                    "--framer-letter-spacing": "-4px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                  },
                                  children: "Two Weeks",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-15v7c9o",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "OfLkph7iZ",
                      style: { opacity: 0.7 },
                      transformTemplate: transformTemplate1,
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial", monospace',
                              "--framer-font-size": "14px",
                              "--framer-line-height": "150%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(87, 87, 87))",
                              "--framer-text-transform": "uppercase",
                            },
                            children:
                              "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                          }),
                        }),
                        className: "framer-1nt067b",
                        "data-framer-name": "Description",
                        "data-highlight": true,
                        fonts: ["GF;GT Flexa Mono Trial-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "mTy0ql7OZ",
                        onTap: onTap1o2v8hv,
                        style: {
                          "--extracted-r6o4lv": "rgb(87, 87, 87)",
                          "--framer-paragraph-spacing": "0px",
                        },
                        variants: {
                          "ddKSdeclD-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                          },
                          "X_SXtY5JO-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                          },
                          "za7e8QsYt-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                          },
                        },
                        verticalAlignment: "center",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "ddKSdeclD-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-font-size": "14px",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                                }),
                              }),
                            },
                            "X_SXtY5JO-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-font-size": "14px",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                                }),
                              }),
                            },
                            "za7e8QsYt-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                                }),
                              }),
                            },
                            za7e8QsYt: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(87, 87, 87))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-ijl9kx",
                      "data-border": true,
                      "data-framer-name": "HorizontalBorder",
                      layoutDependency: layoutDependency,
                      layoutId: "CWP_nVmVZ",
                      style: {
                        "--border-bottom-width": "0px",
                        "--border-color": "rgb(39, 39, 39)",
                        "--border-left-width": "0px",
                        "--border-right-width": "0px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                      },
                    }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-k8gxag",
                      "data-framer-name": "Step Indicator",
                      layoutDependency: layoutDependency,
                      layoutId: "mQotSK8qB",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                              "--framer-font-family":
                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                              "--framer-font-size": "12px",
                              "--framer-letter-spacing": "0px",
                              "--framer-line-height": "12px",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                            },
                            children: "02",
                          }),
                        }),
                        className: "framer-17cx8kv",
                        "data-framer-name": "Step Number",
                        fonts: ["GF;Suisse Int'l-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "GqF1O1Y3O",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          "--framer-paragraph-spacing": "0px",
                        },
                        transformTemplate: transformTemplate2,
                        variants: {
                          "ddKSdeclD-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0))",
                          },
                          "X_SXtY5JO-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0))",
                          },
                        },
                        verticalAlignment: "center",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "ddKSdeclD-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "12px",
                                    "--framer-letter-spacing": "0px",
                                    "--framer-line-height": "12px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0)))",
                                  },
                                  children: "02",
                                }),
                              }),
                            },
                            "X_SXtY5JO-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "12px",
                                    "--framer-letter-spacing": "0px",
                                    "--framer-line-height": "12px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0)))",
                                  },
                                  children: "02",
                                }),
                              }),
                            },
                            "za7e8QsYt-hover": { transformTemplate: undefined },
                            za7e8QsYt: { transformTemplate: undefined },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                ],
              }),
            }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-8qe8yv",
                "data-framer-name": "One Problem",
                layoutDependency: layoutDependency,
                layoutId: "pcs6vSiEm",
                transformTemplate: transformTemplate2,
                children: /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-cay9oz",
                  "data-framer-name": "One Problem",
                  layoutDependency: layoutDependency,
                  layoutId: "HJUYVJycM",
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1w94i5d",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "eqdfz3Hjs",
                      transformTemplate: transformTemplate1,
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1or85d0",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "EiqGt6mso",
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-25a3l4",
                          "data-framer-name": "Container",
                          layoutDependency: layoutDependency,
                          layoutId: "KHuDDVSfb",
                          children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-149mthg",
                            "data-framer-name": "Container",
                            layoutDependency: layoutDependency,
                            layoutId: "GpQSuH8cP",
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "50px",
                                    "--framer-letter-spacing": "-3px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                                  },
                                  children: "Two Weeks",
                                }),
                              }),
                              className: "framer-x2gg6t",
                              "data-framer-name": "Step Title",
                              fonts: ["GF;Suisse Int'l-regular"],
                              layoutDependency: layoutDependency,
                              layoutId: "qYvj1g_Yu",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61))",
                                "--framer-paragraph-spacing": "0px",
                              },
                              variants: {
                                aAMbupUlB: {
                                  "--extracted-a0htzi":
                                    "var(--token-b232f48f-0fe9-46e5-840e-27b7c17897f0, rgb(1, 1, 1))",
                                },
                                t1xg1bIzj: {
                                  "--extracted-a0htzi":
                                    "var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61))",
                                },
                              },
                              verticalAlignment: "center",
                              withExternalLayout: true,
                              ...addPropertyOverrides(
                                {
                                  aAMbupUlB: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(
                                          motion.h3,
                                          {
                                            dir: "auto",
                                            style: {
                                              "--font-selector":
                                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                              "--framer-font-family":
                                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                              "--framer-font-size": "50px",
                                              "--framer-letter-spacing": "-3px",
                                              "--framer-line-height": "76px",
                                              "--framer-text-color":
                                                "var(--extracted-a0htzi, var(--token-b232f48f-0fe9-46e5-840e-27b7c17897f0, rgb(1, 1, 1)))",
                                            },
                                            children: "Two Weeks",
                                          }
                                        ),
                                      }
                                    ),
                                  },
                                  t1xg1bIzj: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(
                                          motion.h3,
                                          {
                                            dir: "auto",
                                            style: {
                                              "--font-selector":
                                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                              "--framer-font-family":
                                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                              "--framer-font-size": "50px",
                                              "--framer-letter-spacing": "-3px",
                                              "--framer-line-height": "76px",
                                              "--framer-text-color":
                                                "var(--extracted-a0htzi, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                                            },
                                            children: "Two Weeks",
                                          }
                                        ),
                                      }
                                    ),
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }),
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-e20dsd",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "a3lQ21I54",
                      children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1qe2ek3",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "JAQ94QXp_",
                        children: [
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1nejoig",
                            "data-framer-name": "Container",
                            layoutDependency: layoutDependency,
                            layoutId: "b7FIYJUh3",
                            style: { opacity: 0.7 },
                          }),
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-170okq7",
                            "data-framer-name": "Container",
                            layoutDependency: layoutDependency,
                            layoutId: "Mp8BiGtfE",
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-font-size": "12px",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                }),
                              }),
                              className: "framer-11l5x41",
                              "data-framer-name": "Description",
                              fonts: ["GF;GT Flexa Mono Trial-regular"],
                              layoutDependency: layoutDependency,
                              layoutId: "WgxHyrTHG",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64))",
                                "--framer-paragraph-spacing": "0px",
                              },
                              variants: {
                                aAMbupUlB: {
                                  "--extracted-r6o4lv":
                                    "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                                },
                              },
                              verticalAlignment: "center",
                              withExternalLayout: true,
                              ...addPropertyOverrides(
                                {
                                  aAMbupUlB: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          style: {
                                            "--font-selector":
                                              "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                            "--framer-font-family":
                                              '"GT Flexa Mono Trial", monospace',
                                            "--framer-font-size": "12px",
                                            "--framer-line-height": "150%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                            "--framer-text-transform":
                                              "uppercase",
                                          },
                                          children:
                                            "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                                        }),
                                      }
                                    ),
                                  },
                                  t1xg1bIzj: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          style: {
                                            "--font-selector":
                                              "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                            "--framer-font-family":
                                              '"GT Flexa Mono Trial", monospace',
                                            "--framer-font-size": "12px",
                                            "--framer-line-height": "150%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                            "--framer-text-transform":
                                              "uppercase",
                                          },
                                          children:
                                            "Like your dev teams, we work in two-week sprints. Once we’ve honed in on a problem, we spend two weeks solving it. Then, we move on to the next.",
                                        }),
                                      }
                                    ),
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }),
                        ],
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-jnmcfl",
                      "data-border": true,
                      "data-framer-name": "HorizontalBorder",
                      layoutDependency: layoutDependency,
                      layoutId: "kGYmJRSdp",
                      style: {
                        "--border-bottom-width": "0px",
                        "--border-color": "rgb(34, 34, 34)",
                        "--border-left-width": "0px",
                        "--border-right-width": "0px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                      },
                    }),
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-1pamvne",
                      "data-framer-name": "Step Indicator",
                      layoutDependency: layoutDependency,
                      layoutId: "ijp0AaLRj",
                      children: [
                        isDisplayed() &&
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1857b8h",
                            "data-framer-name": "Overlay",
                            layoutDependency: layoutDependency,
                            layoutId: "VJAWFfHNy",
                            style: {
                              backgroundColor: "rgba(61, 61, 61, 0.7)",
                              borderBottomLeftRadius: 999,
                              borderBottomRightRadius: 999,
                              borderTopLeftRadius: 999,
                              borderTopRightRadius: 999,
                            },
                          }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "10px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                              },
                              children: "02",
                            }),
                          }),
                          className: "framer-o0j3yw",
                          "data-framer-name": "Step Number",
                          fonts: ["GF;Suisse Int'l-regular"],
                          layoutDependency: layoutDependency,
                          layoutId: "YIoYEBzUm",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                            "--framer-paragraph-spacing": "0px",
                          },
                          transformTemplate: transformTemplate2,
                          variants: {
                            aAMbupUlB: {
                              "--extracted-r6o4lv":
                                "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                            },
                          },
                          verticalAlignment: "center",
                          withExternalLayout: true,
                          ...addPropertyOverrides(
                            {
                              aAMbupUlB: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                      "--framer-font-size": "10px",
                                      "--framer-letter-spacing": "0px",
                                      "--framer-line-height": "12px",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                    },
                                    children: "02",
                                  }),
                                }),
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      ],
                    }),
                  ],
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-prKbP.framer-c2jk9, .framer-prKbP .framer-c2jk9 { display: block; }",
  ".framer-prKbP.framer-1tmqiip { cursor: pointer; gap: 24px; height: 324px; overflow: visible; position: relative; width: 1200px; }",
  ".framer-prKbP .framer-amat49 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; top: 67px; width: 100%; }",
  ".framer-prKbP .framer-1cy3dko { flex: none; height: 249px; overflow: visible; position: relative; width: 914px; }",
  ".framer-prKbP .framer-16a4ulo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 0px; width: 422px; }",
  ".framer-prKbP .framer-18zpv0k, .framer-prKbP .framer-x2gg6t { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-prKbP .framer-15v7c9o { align-content: flex-start; align-items: flex-start; bottom: 63px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 0px; position: absolute; width: min-content; }",
  ".framer-prKbP .framer-1nt067b { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 473px; word-break: break-word; word-wrap: break-word; }",
  ".framer-prKbP .framer-ijl9kx { bottom: 0px; flex: none; height: 149px; left: 0px; position: absolute; right: 0px; }",
  ".framer-prKbP .framer-k8gxag { flex: none; height: 21px; left: 210px; overflow: visible; position: absolute; top: 0px; width: 21px; }",
  ".framer-prKbP .framer-17cx8kv { flex: none; height: auto; left: 52%; position: absolute; top: 52%; white-space: pre; width: auto; }",
  ".framer-prKbP .framer-8qe8yv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; top: 50%; width: 325px; }",
  ".framer-prKbP .framer-cay9oz { flex: none; gap: 24px; height: 212px; overflow: visible; position: relative; width: 325px; }",
  ".framer-prKbP .framer-1w94i5d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 0px; width: min-content; }",
  ".framer-prKbP .framer-1or85d0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-prKbP .framer-25a3l4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-prKbP .framer-149mthg, .framer-prKbP .framer-170okq7 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-prKbP .framer-e20dsd { align-content: center; align-items: center; bottom: 21px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; width: 100%; }",
  ".framer-prKbP .framer-1qe2ek3 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 16px 0px 16px; position: relative; width: 1px; }",
  ".framer-prKbP .framer-1nejoig { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; min-height: 108px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-prKbP .framer-11l5x41 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-prKbP .framer-jnmcfl { bottom: 0px; flex: none; height: 127px; left: 0px; position: absolute; width: 100%; }",
  ".framer-prKbP .framer-1pamvne { flex: none; height: 21px; left: calc(10.769230769230791% - 21px / 2); overflow: visible; position: absolute; top: calc(7.547169811320777% - 21px / 2); width: 21px; }",
  ".framer-prKbP .framer-1857b8h { flex: none; height: 21px; left: calc(47.61904761904764% - 21px / 2); position: absolute; top: calc(47.61904761904764% - 21px / 2); width: 21px; }",
  ".framer-prKbP .framer-o0j3yw { flex: none; height: auto; left: 48%; position: absolute; top: 52%; white-space: pre; width: auto; }",
  ".framer-prKbP.framer-v-1ksxphj.framer-1tmqiip { width: 810px; }",
  ".framer-prKbP.framer-v-1ksxphj .framer-1cy3dko { height: 252px; width: 810px; }",
  ".framer-prKbP.framer-v-1ksxphj .framer-16a4ulo { left: 50%; top: 5px; }",
  ".framer-prKbP.framer-v-1ksxphj .framer-18zpv0k, .framer-prKbP.framer-v-idoy5d .framer-1nejoig, .framer-prKbP.framer-v-mtlfhl .framer-1nejoig { order: 0; }",
  ".framer-prKbP.framer-v-1ksxphj .framer-ijl9kx { left: calc(50.00000000000002% - 635px / 2); right: unset; width: 635px; }",
  ".framer-prKbP.framer-v-1ksxphj .framer-k8gxag { left: 169px; }",
  ".framer-prKbP.framer-v-idoy5d.framer-1tmqiip, .framer-prKbP.framer-v-mtlfhl.framer-1tmqiip { cursor: unset; width: 390px; }",
  ".framer-prKbP.framer-v-idoy5d .framer-170okq7, .framer-prKbP.framer-v-mtlfhl .framer-170okq7 { order: 1; }",
  ".framer-prKbP.framer-v-169avwo.framer-1tmqiip, .framer-prKbP.framer-v-169avwo .framer-1cy3dko { width: 1512px; }",
  ".framer-prKbP.framer-v-169avwo .framer-amat49 { height: 249px; right: 0px; width: unset; }",
  ".framer-prKbP.framer-v-169avwo .framer-16a4ulo { left: 50%; }",
  ".framer-prKbP.framer-v-169avwo .framer-15v7c9o { align-content: center; align-items: center; justify-content: center; width: 1000px; }",
  ".framer-prKbP.framer-v-169avwo .framer-1nt067b { width: 100%; }",
  ".framer-prKbP.framer-v-169avwo .framer-ijl9kx { bottom: 5px; left: 156px; right: 156px; }",
  ".framer-prKbP.framer-v-169avwo .framer-k8gxag { left: 507px; }",
  ".framer-prKbP.framer-v-169avwo .framer-17cx8kv { bottom: 4px; left: unset; right: 5px; top: unset; }",
  ".framer-prKbP.framer-v-1ksxphj.hover .framer-ijl9kx { left: calc(50.617283950617306% - 635px / 2); right: unset; }",
  ".framer-prKbP.framer-v-169avwo.hover .framer-amat49 { width: unset; }",
  ".framer-prKbP.framer-v-169avwo.hover .framer-17cx8kv { left: unset; top: unset; }",
  '.framer-prKbP[data-border="true"]::after, .framer-prKbP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 324
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ddKSdeclD":{"layout":["fixed","fixed"]},"t1xg1bIzj":{"layout":["fixed","fixed"]},"za7e8QsYt":{"layout":["fixed","fixed"]},"aAMbupUlB":{"layout":["fixed","fixed"]},"nax4eU4j7":{"layout":["fixed","fixed"]},"X50jkAjg9":{"layout":["fixed","fixed"]},"SiHClMKsj":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerXwnVXJrEF = withCSS(Component, css, "framer-prKbP");
export default FramerXwnVXJrEF;
FramerXwnVXJrEF.displayName = "box-2";
FramerXwnVXJrEF.defaultProps = { height: 324, width: 1200 };
addPropertyControls(FramerXwnVXJrEF, {
  variant: {
    options: ["X_SXtY5JO", "ddKSdeclD", "t1xg1bIzj", "za7e8QsYt", "aAMbupUlB"],
    optionTitles: [
      "Variant 1",
      "Variant 2",
      "Variant 3",
      "Variant 4",
      "Variant 5",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerXwnVXJrEF, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerXwnVXJrEF",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicWidth: "1200",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ddKSdeclD":{"layout":["fixed","fixed"]},"t1xg1bIzj":{"layout":["fixed","fixed"]},"za7e8QsYt":{"layout":["fixed","fixed"]},"aAMbupUlB":{"layout":["fixed","fixed"]},"nax4eU4j7":{"layout":["fixed","fixed"]},"X50jkAjg9":{"layout":["fixed","fixed"]},"SiHClMKsj":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "324",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./XwnVXJrEF.map
