// Generated by Framer (98b71dc)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Image2 from "https://framerusercontent.com/modules/a1Swq9oyfe3voRWNdt3Y/odkbpPWVJGYkGQBBUSjE/uvqbP3sF6.js";
const Image2Fonts = getFonts(Image2);
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
  CWOdV49Al: { hover: true },
  yfYQyB_FX: { hover: true },
};
const cycleOrder = ["CWOdV49Al", "yfYQyB_FX", "xRmN_JAPF"];
const serializationHash = "framer-KUxA3";
const variantClassNames = {
  CWOdV49Al: "framer-v-1x1fsdm",
  xRmN_JAPF: "framer-v-r7126h",
  yfYQyB_FX: "framer-v-7znw8o",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
  const [visible, setVisible] = useOverlayState({ blockDocumentScrolling });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "no hover": "xRmN_JAPF",
  "Variant 1": "CWOdV49Al",
  "Variant 2": "yfYQyB_FX",
};
const getProps = ({ fontSize, height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "CWOdV49Al",
    y8pEg3AXY: fontSize ?? props.y8pEg3AXY ?? 42,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, y8pEg3AXY, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "CWOdV49Al",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnterupml6a = ({ overlay, loadMore }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isHovered: true });
      overlay.show();
    });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "yfYQyB_FX-hover") return true;
    return false;
  };
  const ref1 = React.useRef(null);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Overlay, {
        blockDocumentScrolling: false,
        enabled: isDisplayed(),
        children: (overlay) =>
          /*#__PURE__*/ _jsx(_Fragment, {
            children: /*#__PURE__*/ _jsx(Transition, {
              value: transition1,
              children: /*#__PURE__*/ _jsxs(motion.div, {
                ...restProps,
                ...gestureHandlers,
                className: cx(
                  scopingClassNames,
                  "framer-1x1fsdm",
                  className,
                  classNames
                ),
                "data-framer-name": "Variant 1",
                "data-highlight": true,
                id: `${layoutId}-1x1fsdm`,
                layoutDependency: layoutDependency,
                layoutId: "CWOdV49Al",
                onMouseEnter: onMouseEnterupml6a({ overlay }),
                ref: refBinding,
                style: { ...style },
                ...addPropertyOverrides(
                  {
                    "CWOdV49Al-hover": { "data-framer-name": undefined },
                    "yfYQyB_FX-hover": { "data-framer-name": undefined },
                    xRmN_JAPF: { "data-framer-name": "no hover" },
                    yfYQyB_FX: { "data-framer-name": "Variant 2" },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-qvg75s",
                    layoutDependency: layoutDependency,
                    layoutId: "XsyQX8rzE",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-y8pEg3AXY-Q46aamimZ) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "002.",
                          }),
                        }),
                        className: "framer-dwid6y",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "cApQE_MmK",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-y8pEg3AXY-Q46aamimZ": y8pEg3AXY,
                        },
                        variants: {
                          "CWOdV49Al-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                          "yfYQyB_FX-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "CWOdV49Al-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-y8pEg3AXY-Q46aamimZ) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "002",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "yfYQyB_FX-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-y8pEg3AXY-Q46aamimZ) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "002",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-y8pEg3AXY-Q46aamimZ) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "HAVE A POINT OF VIEW.",
                          }),
                        }),
                        className: "framer-w8sape",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "J2l3UEtvO",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-y8pEg3AXY-Q46aamimZ": y8pEg3AXY,
                        },
                        variants: {
                          "CWOdV49Al-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                          "yfYQyB_FX-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "CWOdV49Al-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-y8pEg3AXY-Q46aamimZ) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "HAVE A POINT OF VIEW",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "yfYQyB_FX-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-y8pEg3AXY-Q46aamimZ) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "HAVE A POINT OF VIEW",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    ],
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(AnimatePresence, {
                      children:
                        overlay.visible &&
                        /*#__PURE__*/ _jsx(Floating, {
                          alignment: "center",
                          anchorRef: refBinding,
                          className: cx(scopingClassNames, classNames),
                          collisionDetection: true,
                          collisionDetectionPadding: 20,
                          "data-framer-portal-id": `${layoutId}-1x1fsdm`,
                          offsetX: 0,
                          offsetY: 10,
                          onDismiss: overlay.hide,
                          placement: "bottom",
                          safeArea: true,
                          zIndex: 11,
                          children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation1,
                            className: "framer-yfwcr1",
                            exit: animation,
                            initial: animation2,
                            layoutDependency: layoutDependency,
                            layoutId: "D3L6h_2yo",
                            ref: ref1,
                            role: "dialog",
                            style: {
                              backgroundColor: "rgb(255, 255, 255)",
                              borderBottomLeftRadius: 10,
                              borderBottomRightRadius: 10,
                              borderTopLeftRadius: 10,
                              borderTopRightRadius: 10,
                              boxShadow:
                                "0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
                            },
                            variants: {
                              "yfYQyB_FX-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                boxShadow: "none",
                              },
                            },
                            children:
                              isDisplayed() &&
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                ...addPropertyOverrides(
                                  { "yfYQyB_FX-hover": { width: "230px" } },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-157gh0s-container",
                                    "data-framer-name": "002",
                                    layoutDependency: layoutDependency,
                                    layoutId: "VMzR_vW3k-container",
                                    name: "002",
                                    nodeId: "VMzR_vW3k",
                                    rendersWithMotion: true,
                                    scopeId: "Q46aamimZ",
                                    children: /*#__PURE__*/ _jsx(Image2, {
                                      height: "100%",
                                      id: "VMzR_vW3k",
                                      layoutId: "VMzR_vW3k",
                                      name: "002",
                                      style: { height: "100%", width: "100%" },
                                      variant: "Vha7h1OaT",
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }),
                          }),
                        }),
                    }),
                ],
              }),
            }),
          }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-KUxA3.framer-8i2s17, .framer-KUxA3 .framer-8i2s17 { display: block; }",
  ".framer-KUxA3.framer-1x1fsdm { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
  ".framer-KUxA3 .framer-qvg75s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-KUxA3 .framer-dwid6y { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-KUxA3 .framer-w8sape { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-KUxA3 .framer-yfwcr1 { height: 150px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-KUxA3 .framer-157gh0s-container { flex: none; height: 220px; left: calc(51.538461538461554% - 230px / 2); position: absolute; top: 0px; width: 230px; }",
  ".framer-KUxA3.framer-v-r7126h.framer-1x1fsdm { cursor: unset; }",
  ".framer-KUxA3.framer-v-7znw8o.hover .framer-yfwcr1 { height: 160px; width: 260px; }",
  ".framer-KUxA3.framer-v-7znw8o.hover .framer-157gh0s-container { bottom: 0px; height: unset; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 50.5
 * @framerIntrinsicWidth 1100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"yfYQyB_FX":{"layout":["fixed","auto"]},"xRmN_JAPF":{"layout":["fixed","auto"]},"fZm49rnJh":{"layout":["fixed","auto"]},"wYR9rjR4E":{"layout":["fixed","auto"]}}}
 * @framerVariables {"y8pEg3AXY":"fontSize"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerQ46aamimZ = withCSS(Component, css, "framer-KUxA3");
export default FramerQ46aamimZ;
FramerQ46aamimZ.displayName = "002";
FramerQ46aamimZ.defaultProps = { height: 50.5, width: 1100 };
addPropertyControls(FramerQ46aamimZ, {
  variant: {
    options: ["CWOdV49Al", "yfYQyB_FX", "xRmN_JAPF"],
    optionTitles: ["Variant 1", "Variant 2", "no hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
  y8pEg3AXY: { defaultValue: 42, title: "Font Size", type: ControlType.Number },
});
addFonts(
  FramerQ46aamimZ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "GT Flexa Mono Trial Md",
          source: "custom",
          uiFamilyName: "GT Flexa Mono Trial Md",
          url: "https://framerusercontent.com/assets/bytIjhUjhiCYHWtmBe4nrOXxwJM.woff2",
        },
      ],
    },
    ...Image2Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerQ46aamimZ",
      slots: [],
      annotations: {
        framerVariables: '{"y8pEg3AXY":"fontSize"}',
        framerContractVersion: "1",
        framerIntrinsicHeight: "50.5",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"yfYQyB_FX":{"layout":["fixed","auto"]},"xRmN_JAPF":{"layout":["fixed","auto"]},"fZm49rnJh":{"layout":["fixed","auto"]},"wYR9rjR4E":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "1100",
        framerColorSyntax: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Q46aamimZ.map
