// Generated by Framer (98b71dc)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Image6 from "https://framerusercontent.com/modules/8knddiSQfMqjl65d2R3O/qX8qvHO09s9lo5mFLEqD/Ja4TZJ3US.js";
const Image6Fonts = getFonts(Image6);
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
  erl5cTk7q: { hover: true },
  LPBQ6UR9d: { hover: true },
};
const cycleOrder = ["LPBQ6UR9d", "erl5cTk7q", "FsGb6sQOf"];
const serializationHash = "framer-lFrJe";
const variantClassNames = {
  erl5cTk7q: "framer-v-funb6o",
  FsGb6sQOf: "framer-v-fno683",
  LPBQ6UR9d: "framer-v-1tk65dt",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
  const [visible, setVisible] = useOverlayState({ blockDocumentScrolling });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "no hover": "FsGb6sQOf",
  "Variant 1": "LPBQ6UR9d",
  "Variant 2": "erl5cTk7q",
};
const getProps = ({ fontSize, height, id, width, ...props }) => {
  return {
    ...props,
    nxCfXb8_4: fontSize ?? props.nxCfXb8_4 ?? 42,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "LPBQ6UR9d",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, nxCfXb8_4, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "LPBQ6UR9d",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnterupml6a = ({ overlay, loadMore }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isHovered: true });
      overlay.show();
    });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "erl5cTk7q-hover") return true;
    return false;
  };
  const ref1 = React.useRef(null);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Overlay, {
        blockDocumentScrolling: false,
        enabled: isDisplayed(),
        children: (overlay) =>
          /*#__PURE__*/ _jsx(_Fragment, {
            children: /*#__PURE__*/ _jsx(Transition, {
              value: transition1,
              children: /*#__PURE__*/ _jsxs(motion.div, {
                ...restProps,
                ...gestureHandlers,
                className: cx(
                  scopingClassNames,
                  "framer-1tk65dt",
                  className,
                  classNames
                ),
                "data-framer-name": "Variant 1",
                "data-highlight": true,
                id: `${layoutId}-1tk65dt`,
                layoutDependency: layoutDependency,
                layoutId: "LPBQ6UR9d",
                onMouseEnter: onMouseEnterupml6a({ overlay }),
                ref: refBinding,
                style: { ...style },
                ...addPropertyOverrides(
                  {
                    "erl5cTk7q-hover": { "data-framer-name": undefined },
                    "LPBQ6UR9d-hover": { "data-framer-name": undefined },
                    erl5cTk7q: { "data-framer-name": "Variant 2" },
                    FsGb6sQOf: { "data-framer-name": "no hover" },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-nig4zc",
                    layoutDependency: layoutDependency,
                    layoutId: "TCWxZF0W4",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-nxCfXb8_4-MFk4ZuMs2) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "006.",
                          }),
                        }),
                        className: "framer-2yo5ll",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "I0nBEl3qE",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-nxCfXb8_4-MFk4ZuMs2": nxCfXb8_4,
                        },
                        variants: {
                          "erl5cTk7q-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                          "LPBQ6UR9d-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "erl5cTk7q-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nxCfXb8_4-MFk4ZuMs2) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "006",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "LPBQ6UR9d-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nxCfXb8_4-MFk4ZuMs2) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "006",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-nxCfXb8_4-MFk4ZuMs2) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "DON'T TAKE NO SHIT.",
                          }),
                        }),
                        className: "framer-e8lmbj",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "avIeyy6wq",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-nxCfXb8_4-MFk4ZuMs2": nxCfXb8_4,
                        },
                        variants: {
                          "erl5cTk7q-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                          "LPBQ6UR9d-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "erl5cTk7q-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nxCfXb8_4-MFk4ZuMs2) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "DON'T TAKE NO SHIT",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "LPBQ6UR9d-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nxCfXb8_4-MFk4ZuMs2) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "DON'T TAKE NO SHIT",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    ],
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(AnimatePresence, {
                      children:
                        overlay.visible &&
                        /*#__PURE__*/ _jsx(Floating, {
                          alignment: "center",
                          anchorRef: refBinding,
                          className: cx(scopingClassNames, classNames),
                          collisionDetection: true,
                          collisionDetectionPadding: 20,
                          "data-framer-portal-id": `${layoutId}-1tk65dt`,
                          offsetX: 0,
                          offsetY: 10,
                          onDismiss: overlay.hide,
                          placement: "bottom",
                          safeArea: true,
                          zIndex: 11,
                          children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation1,
                            className: "framer-1o74qtt",
                            exit: animation,
                            initial: animation2,
                            layoutDependency: layoutDependency,
                            layoutId: "MChUpPgBY",
                            ref: ref1,
                            role: "dialog",
                            style: {
                              backgroundColor: "rgb(255, 255, 255)",
                              borderBottomLeftRadius: 10,
                              borderBottomRightRadius: 10,
                              borderTopLeftRadius: 10,
                              borderTopRightRadius: 10,
                              boxShadow:
                                "0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
                            },
                            variants: {
                              "erl5cTk7q-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                boxShadow: "none",
                              },
                            },
                            children: /*#__PURE__*/ _jsx(
                              ComponentViewportProvider,
                              {
                                width: "178px",
                                ...addPropertyOverrides(
                                  { "erl5cTk7q-hover": { width: "221px" } },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-yyi42o-container",
                                    "data-framer-name": "006",
                                    layoutDependency: layoutDependency,
                                    layoutId: "LRCqyk6bu-container",
                                    name: "006",
                                    nodeId: "LRCqyk6bu",
                                    rendersWithMotion: true,
                                    scopeId: "MFk4ZuMs2",
                                    children: /*#__PURE__*/ _jsx(Image6, {
                                      height: "100%",
                                      id: "LRCqyk6bu",
                                      layoutId: "LRCqyk6bu",
                                      name: "006",
                                      style: { height: "100%", width: "100%" },
                                      variant: "qGmyG5iXs",
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }
                            ),
                          }),
                        }),
                    }),
                ],
              }),
            }),
          }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-lFrJe.framer-101kguc, .framer-lFrJe .framer-101kguc { display: block; }",
  ".framer-lFrJe.framer-1tk65dt { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
  ".framer-lFrJe .framer-nig4zc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-lFrJe .framer-2yo5ll { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-lFrJe .framer-e8lmbj { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-lFrJe .framer-1o74qtt { height: 150px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-lFrJe .framer-yyi42o-container { flex: none; height: 220px; left: 0px; position: absolute; top: 0px; width: 178px; }",
  ".framer-lFrJe.framer-v-fno683.framer-1tk65dt { cursor: unset; }",
  ".framer-lFrJe.framer-v-funb6o.hover .framer-1o74qtt { height: 223px; width: 260px; }",
  ".framer-lFrJe.framer-v-funb6o.hover .framer-yyi42o-container { height: 154px; left: calc(51.153846153846175% - 221px / 2); width: 221px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 50.5
 * @framerIntrinsicWidth 1100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"erl5cTk7q":{"layout":["fixed","auto"]},"FsGb6sQOf":{"layout":["fixed","auto"]},"Vk9GrLjrW":{"layout":["fixed","auto"]},"F46K_0TRm":{"layout":["fixed","auto"]}}}
 * @framerVariables {"nxCfXb8_4":"fontSize"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerMFk4ZuMs2 = withCSS(Component, css, "framer-lFrJe");
export default FramerMFk4ZuMs2;
FramerMFk4ZuMs2.displayName = "006";
FramerMFk4ZuMs2.defaultProps = { height: 50.5, width: 1100 };
addPropertyControls(FramerMFk4ZuMs2, {
  variant: {
    options: ["LPBQ6UR9d", "erl5cTk7q", "FsGb6sQOf"],
    optionTitles: ["Variant 1", "Variant 2", "no hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
  nxCfXb8_4: { defaultValue: 42, title: "Font Size", type: ControlType.Number },
});
addFonts(
  FramerMFk4ZuMs2,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "GT Flexa Mono Trial Md",
          source: "custom",
          uiFamilyName: "GT Flexa Mono Trial Md",
          url: "https://framerusercontent.com/assets/bytIjhUjhiCYHWtmBe4nrOXxwJM.woff2",
        },
      ],
    },
    ...Image6Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerMFk4ZuMs2",
      slots: [],
      annotations: {
        framerVariables: '{"nxCfXb8_4":"fontSize"}',
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "1100",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "50.5",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"erl5cTk7q":{"layout":["fixed","auto"]},"FsGb6sQOf":{"layout":["fixed","auto"]},"Vk9GrLjrW":{"layout":["fixed","auto"]},"F46K_0TRm":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./MFk4ZuMs2.map
