// Generated by Framer (98b71dc)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Image10 from "https://framerusercontent.com/modules/zuWkNwQY5TEl00Hy4tj7/k2ZGHcPjQRXXbmc2syPM/hWBtPB8Yc.js";
const Image10Fonts = getFonts(Image10);
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
  J6UXDyf4d: { hover: true },
  wNiEZfSeL: { hover: true },
};
const cycleOrder = ["J6UXDyf4d", "wNiEZfSeL", "t9XbEHD6W"];
const serializationHash = "framer-xLrt9";
const variantClassNames = {
  J6UXDyf4d: "framer-v-mdscv8",
  t9XbEHD6W: "framer-v-qlsfrs",
  wNiEZfSeL: "framer-v-1n77p4n",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
  const [visible, setVisible] = useOverlayState({ blockDocumentScrolling });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "no hover": "t9XbEHD6W",
  "Variant 1": "J6UXDyf4d",
  "Variant 2": "wNiEZfSeL",
};
const getProps = ({ fontSize, height, id, width, ...props }) => {
  return {
    ...props,
    lqxc0YIRE: fontSize ?? props.lqxc0YIRE ?? 42,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "J6UXDyf4d",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, lqxc0YIRE, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "J6UXDyf4d",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnterupml6a = ({ overlay, loadMore }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isHovered: true });
      overlay.show();
    });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "wNiEZfSeL-hover") return true;
    return false;
  };
  const ref1 = React.useRef(null);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Overlay, {
        blockDocumentScrolling: false,
        enabled: isDisplayed(),
        children: (overlay) =>
          /*#__PURE__*/ _jsx(_Fragment, {
            children: /*#__PURE__*/ _jsx(Transition, {
              value: transition1,
              children: /*#__PURE__*/ _jsxs(motion.div, {
                ...restProps,
                ...gestureHandlers,
                className: cx(
                  scopingClassNames,
                  "framer-mdscv8",
                  className,
                  classNames
                ),
                "data-framer-name": "Variant 1",
                "data-highlight": true,
                id: `${layoutId}-mdscv8`,
                layoutDependency: layoutDependency,
                layoutId: "J6UXDyf4d",
                onMouseEnter: onMouseEnterupml6a({ overlay }),
                ref: refBinding,
                style: { ...style },
                ...addPropertyOverrides(
                  {
                    "J6UXDyf4d-hover": { "data-framer-name": undefined },
                    "wNiEZfSeL-hover": { "data-framer-name": undefined },
                    t9XbEHD6W: { "data-framer-name": "no hover" },
                    wNiEZfSeL: { "data-framer-name": "Variant 2" },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-zqicf0",
                    layoutDependency: layoutDependency,
                    layoutId: "tCxRTKSrO",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-lqxc0YIRE-Q79pwa3u3) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "010.",
                          }),
                        }),
                        className: "framer-k8z38d",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "xzlZtO0J0",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-lqxc0YIRE-Q79pwa3u3": lqxc0YIRE,
                        },
                        variants: {
                          "J6UXDyf4d-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                          "wNiEZfSeL-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "J6UXDyf4d-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-lqxc0YIRE-Q79pwa3u3) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "010",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "wNiEZfSeL-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-lqxc0YIRE-Q79pwa3u3) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "010",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-lqxc0YIRE-Q79pwa3u3) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children:
                              "IF YOU AREN'T PISSING SOMEONE OFF, YOU'RE DOING SOMETHING WRONG.",
                          }),
                        }),
                        className: "framer-8svlfa",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "F27o22eS8",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-lqxc0YIRE-Q79pwa3u3": lqxc0YIRE,
                        },
                        variants: {
                          "J6UXDyf4d-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                          "wNiEZfSeL-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "J6UXDyf4d-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-lqxc0YIRE-Q79pwa3u3) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "IF YOU AREN'T PISSING SOMEONE OFF, YOU'RE DOING SOMETHING WRONG",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "wNiEZfSeL-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-lqxc0YIRE-Q79pwa3u3) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "IF YOU AREN'T PISSING SOMEONE OFF, YOU'RE DOING SOMETHING WRONG",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    ],
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(AnimatePresence, {
                      children:
                        overlay.visible &&
                        /*#__PURE__*/ _jsx(Floating, {
                          alignment: "center",
                          anchorRef: refBinding,
                          className: cx(scopingClassNames, classNames),
                          collisionDetection: true,
                          collisionDetectionPadding: 20,
                          "data-framer-portal-id": `${layoutId}-mdscv8`,
                          offsetX: 0,
                          offsetY: 10,
                          onDismiss: overlay.hide,
                          placement: "bottom",
                          safeArea: true,
                          zIndex: 11,
                          children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation1,
                            className: "framer-gfh92g",
                            exit: animation,
                            initial: animation2,
                            layoutDependency: layoutDependency,
                            layoutId: "GgWi0beXV",
                            ref: ref1,
                            role: "dialog",
                            style: {
                              backgroundColor: "rgb(255, 255, 255)",
                              borderBottomLeftRadius: 10,
                              borderBottomRightRadius: 10,
                              borderTopLeftRadius: 10,
                              borderTopRightRadius: 10,
                              boxShadow:
                                "0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
                            },
                            variants: {
                              "wNiEZfSeL-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                boxShadow: "none",
                              },
                            },
                            children: /*#__PURE__*/ _jsx(
                              ComponentViewportProvider,
                              {
                                width: "178px",
                                ...addPropertyOverrides(
                                  { "wNiEZfSeL-hover": { width: "222px" } },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-e9dcfa-container",
                                    "data-framer-name": "010",
                                    layoutDependency: layoutDependency,
                                    layoutId: "NUPczU8aV-container",
                                    name: "010",
                                    nodeId: "NUPczU8aV",
                                    rendersWithMotion: true,
                                    scopeId: "Q79pwa3u3",
                                    children: /*#__PURE__*/ _jsx(Image10, {
                                      height: "100%",
                                      id: "NUPczU8aV",
                                      layoutId: "NUPczU8aV",
                                      name: "010",
                                      style: { height: "100%", width: "100%" },
                                      variant: "clYsAAFc8",
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }
                            ),
                          }),
                        }),
                    }),
                ],
              }),
            }),
          }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-xLrt9.framer-1mtwsku, .framer-xLrt9 .framer-1mtwsku { display: block; }",
  ".framer-xLrt9.framer-mdscv8 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
  ".framer-xLrt9 .framer-zqicf0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-xLrt9 .framer-k8z38d { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-xLrt9 .framer-8svlfa { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-xLrt9 .framer-gfh92g { height: 150px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-xLrt9 .framer-e9dcfa-container { flex: none; height: 220px; left: 0px; position: absolute; top: 0px; width: 178px; }",
  ".framer-xLrt9.framer-v-qlsfrs.framer-mdscv8 { cursor: unset; }",
  ".framer-xLrt9.framer-v-1n77p4n.hover .framer-gfh92g { height: 160px; width: 260px; }",
  ".framer-xLrt9.framer-v-1n77p4n.hover .framer-e9dcfa-container { bottom: 0px; height: unset; left: calc(50.00000000000002% - 222px / 2); width: 222px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 101
 * @framerIntrinsicWidth 1100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wNiEZfSeL":{"layout":["fixed","auto"]},"t9XbEHD6W":{"layout":["fixed","auto"]},"MzrjZdOqj":{"layout":["fixed","auto"]},"NSVh03L1E":{"layout":["fixed","auto"]}}}
 * @framerVariables {"lqxc0YIRE":"fontSize"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerQ79pwa3u3 = withCSS(Component, css, "framer-xLrt9");
export default FramerQ79pwa3u3;
FramerQ79pwa3u3.displayName = "010";
FramerQ79pwa3u3.defaultProps = { height: 101, width: 1100 };
addPropertyControls(FramerQ79pwa3u3, {
  variant: {
    options: ["J6UXDyf4d", "wNiEZfSeL", "t9XbEHD6W"],
    optionTitles: ["Variant 1", "Variant 2", "no hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
  lqxc0YIRE: { defaultValue: 42, title: "Font Size", type: ControlType.Number },
});
addFonts(
  FramerQ79pwa3u3,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "GT Flexa Mono Trial Md",
          source: "custom",
          uiFamilyName: "GT Flexa Mono Trial Md",
          url: "https://framerusercontent.com/assets/bytIjhUjhiCYHWtmBe4nrOXxwJM.woff2",
        },
      ],
    },
    ...Image10Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerQ79pwa3u3",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wNiEZfSeL":{"layout":["fixed","auto"]},"t9XbEHD6W":{"layout":["fixed","auto"]},"MzrjZdOqj":{"layout":["fixed","auto"]},"NSVh03L1E":{"layout":["fixed","auto"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "101",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "1100",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerVariables: '{"lqxc0YIRE":"fontSize"}',
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Q79pwa3u3.map
