// Generated by Framer (a1ad18b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = {
  dPHUZjnq6: { hover: true },
  l8mCqTv73: { hover: true },
  WcR3QIn90: { hover: true },
};
const cycleOrder = [
  "l8mCqTv73",
  "WcR3QIn90",
  "N5hCQMb7r",
  "dPHUZjnq6",
  "UGRdVJ0L7",
];
const serializationHash = "framer-ZFAOn";
const variantClassNames = {
  dPHUZjnq6: "framer-v-1k3d7nd",
  l8mCqTv73: "framer-v-d57yq7",
  N5hCQMb7r: "framer-v-1k8olky",
  UGRdVJ0L7: "framer-v-1pddxag",
  WcR3QIn90: "framer-v-1wpmnmv",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const transformTemplate3 = (_, t) => `translateY(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "l8mCqTv73",
  "Variant 2": "WcR3QIn90",
  "Variant 3": "N5hCQMb7r",
  "Variant 4": "dPHUZjnq6",
  "Variant 5": "UGRdVJ0L7",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "l8mCqTv73",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "l8mCqTv73",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["N5hCQMb7r", "UGRdVJ0L7"].includes(baseVariant)) return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (["N5hCQMb7r", "UGRdVJ0L7"].includes(baseVariant)) return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-d57yq7",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "l8mCqTv73",
          ref: refBinding,
          style: {
            backgroundColor: "rgba(0, 0, 0, 0)",
            boxShadow: "none",
            ...style,
          },
          variants: {
            "dPHUZjnq6-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow: "0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            "l8mCqTv73-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow: "0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            "WcR3QIn90-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow: "0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            UGRdVJ0L7: {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
              boxShadow: "0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
          },
          ...addPropertyOverrides(
            {
              "dPHUZjnq6-hover": { "data-framer-name": undefined },
              "l8mCqTv73-hover": { "data-framer-name": undefined },
              "WcR3QIn90-hover": { "data-framer-name": undefined },
              dPHUZjnq6: { "data-framer-name": "Variant 4" },
              N5hCQMb7r: { "data-framer-name": "Variant 3" },
              UGRdVJ0L7: { "data-framer-name": "Variant 5" },
              WcR3QIn90: { "data-framer-name": "Variant 2" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-d3hr9n",
              layoutDependency: layoutDependency,
              layoutId: "KhOs9e5N8",
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-q5t0p9",
                layoutDependency: layoutDependency,
                layoutId: "NDy3lA4re",
                children: [
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-18110dc",
                      layoutDependency: layoutDependency,
                      layoutId: "jUoeV9bM6",
                      transformTemplate: transformTemplate1,
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial", monospace',
                              "--framer-font-size": "14px",
                              "--framer-line-height": "150%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                              "--framer-text-transform": "uppercase",
                            },
                            children:
                              "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                          }),
                        }),
                        className: "framer-dbrsu7",
                        "data-framer-name": "Description",
                        fonts: ["GF;GT Flexa Mono Trial-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "d7HORiYSH",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64))",
                          "--framer-paragraph-spacing": "0px",
                        },
                        variants: {
                          "dPHUZjnq6-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                          },
                          "l8mCqTv73-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                          },
                          "WcR3QIn90-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                          },
                        },
                        verticalAlignment: "center",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "dPHUZjnq6-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                                }),
                              }),
                            },
                            "l8mCqTv73-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-font-size": "14px",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                                }),
                              }),
                            },
                            "WcR3QIn90-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-font-size": "14px",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                                }),
                              }),
                            },
                            dPHUZjnq6: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-egec4q",
                      layoutDependency: layoutDependency,
                      layoutId: "nzcmVIfIm",
                      transformTemplate: transformTemplate1,
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h3, {
                            dir: "auto",
                            style: {
                              "--font-selector":
                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                              "--framer-font-family":
                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                              "--framer-font-size": "88px",
                              "--framer-letter-spacing": "-4px",
                              "--framer-line-height": "76px",
                              "--framer-text-color":
                                "var(--extracted-a0htzi, var(--token-7f4bbc69-c774-4c56-ac41-d2c49301020e, rgb(61, 61, 61)))",
                            },
                            children: "Three Months",
                          }),
                        }),
                        className: "framer-11461ds",
                        "data-framer-name": "Step Title",
                        fonts: ["GF;Suisse Int'l-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "TXeC0bdrK",
                        style: {
                          "--extracted-a0htzi":
                            "var(--token-7f4bbc69-c774-4c56-ac41-d2c49301020e, rgb(61, 61, 61))",
                          "--framer-paragraph-spacing": "0px",
                        },
                        variants: {
                          "dPHUZjnq6-hover": {
                            "--extracted-a0htzi":
                              "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                          },
                          "l8mCqTv73-hover": {
                            "--extracted-a0htzi":
                              "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                          },
                          "WcR3QIn90-hover": {
                            "--extracted-a0htzi":
                              "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                          },
                        },
                        verticalAlignment: "center",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "dPHUZjnq6-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h3, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "88px",
                                    "--framer-letter-spacing": "-4px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-color":
                                      "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                  },
                                  children: "Three Months",
                                }),
                              }),
                            },
                            "l8mCqTv73-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h3, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "88px",
                                    "--framer-letter-spacing": "-4px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-color":
                                      "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                  },
                                  children: "Three Months",
                                }),
                              }),
                            },
                            "WcR3QIn90-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h3, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "88px",
                                    "--framer-letter-spacing": "-4px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-color":
                                      "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                  },
                                  children: "Three Months",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1rk5woj",
                      "data-border": true,
                      "data-framer-name": "HorizontalBorder",
                      layoutDependency: layoutDependency,
                      layoutId: "rLRZdF18M",
                      style: {
                        "--border-bottom-width": "0px",
                        "--border-color": "rgb(34, 34, 34)",
                        "--border-left-width": "0px",
                        "--border-right-width": "0px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                      },
                    }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1hcdmh",
                      "data-framer-name": "Step Indicator",
                      layoutDependency: layoutDependency,
                      layoutId: "KPnK_Meqi",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                              "--framer-font-family":
                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                              "--framer-font-size": "12px",
                              "--framer-letter-spacing": "0px",
                              "--framer-line-height": "12px",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                            },
                            children: "03",
                          }),
                        }),
                        className: "framer-1guuqyp",
                        "data-framer-name": "Step Number",
                        fonts: ["GF;Suisse Int'l-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "cc6_wllEa",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          "--framer-paragraph-spacing": "0px",
                        },
                        transformTemplate: transformTemplate2,
                        variants: {
                          "dPHUZjnq6-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0))",
                          },
                          "l8mCqTv73-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0))",
                          },
                          "WcR3QIn90-hover": {
                            "--extracted-r6o4lv":
                              "var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0))",
                          },
                        },
                        verticalAlignment: "center",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "dPHUZjnq6-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "12px",
                                    "--framer-letter-spacing": "0px",
                                    "--framer-line-height": "12px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0)))",
                                  },
                                  children: "03",
                                }),
                              }),
                              transformTemplate: transformTemplate2,
                            },
                            "l8mCqTv73-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "12px",
                                    "--framer-letter-spacing": "0px",
                                    "--framer-line-height": "12px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0)))",
                                  },
                                  children: "03",
                                }),
                              }),
                            },
                            "WcR3QIn90-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "12px",
                                    "--framer-letter-spacing": "0px",
                                    "--framer-line-height": "12px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0)))",
                                  },
                                  children: "03",
                                }),
                              }),
                            },
                            dPHUZjnq6: {
                              transformTemplate: transformTemplate3,
                            },
                            WcR3QIn90: {
                              transformTemplate: transformTemplate3,
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                ],
              }),
            }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-160sxqb",
                "data-framer-name": "One Problem",
                layoutDependency: layoutDependency,
                layoutId: "F34SGPDa6",
                transformTemplate: transformTemplate2,
                children: /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-zsauux",
                  "data-framer-name": "One Problem",
                  layoutDependency: layoutDependency,
                  layoutId: "S3wIZ3Bwv",
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-151sbie",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "ZwQCDNt6O",
                      transformTemplate: transformTemplate1,
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1y5sysx",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "j5ujUMmMN",
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-15ofuo9",
                          "data-framer-name": "Container",
                          layoutDependency: layoutDependency,
                          layoutId: "I46iWH4P_",
                          children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-bimijk",
                            "data-framer-name": "Container",
                            layoutDependency: layoutDependency,
                            layoutId: "dt7on7Wqw",
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                    "--framer-font-family":
                                      '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                    "--framer-font-size": "50px",
                                    "--framer-letter-spacing": "-3px",
                                    "--framer-line-height": "76px",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                                  },
                                  children: "Three Months",
                                }),
                              }),
                              className: "framer-4w46qo",
                              "data-framer-name": "Step Title",
                              fonts: ["GF;Suisse Int'l-regular"],
                              layoutDependency: layoutDependency,
                              layoutId: "TWw8oUJbK",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61))",
                                "--framer-paragraph-spacing": "0px",
                              },
                              variants: {
                                N5hCQMb7r: {
                                  "--extracted-a0htzi":
                                    "var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61))",
                                },
                                UGRdVJ0L7: {
                                  "--extracted-a0htzi":
                                    "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                                },
                              },
                              verticalAlignment: "center",
                              withExternalLayout: true,
                              ...addPropertyOverrides(
                                {
                                  N5hCQMb7r: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(
                                          motion.h3,
                                          {
                                            dir: "auto",
                                            style: {
                                              "--font-selector":
                                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                              "--framer-font-family":
                                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                              "--framer-font-size": "50px",
                                              "--framer-letter-spacing": "-3px",
                                              "--framer-line-height": "76px",
                                              "--framer-text-color":
                                                "var(--extracted-a0htzi, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                                            },
                                            children: "Three Months",
                                          }
                                        ),
                                      }
                                    ),
                                  },
                                  UGRdVJ0L7: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(
                                          motion.h3,
                                          {
                                            dir: "auto",
                                            style: {
                                              "--font-selector":
                                                "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                              "--framer-font-family":
                                                '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                              "--framer-font-size": "50px",
                                              "--framer-letter-spacing": "-3px",
                                              "--framer-line-height": "76px",
                                              "--framer-text-color":
                                                "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                            },
                                            children: "Three Months",
                                          }
                                        ),
                                      }
                                    ),
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }),
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-wifhv0",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "GlZ2pCZ_W",
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-44v6l1",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "ELMseYDN8",
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-10fkyir",
                          "data-framer-name": "Container",
                          layoutDependency: layoutDependency,
                          layoutId: "usqFJMyYo",
                          style: { opacity: 0.7 },
                          children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-a7289w",
                            "data-framer-name": "Container",
                            layoutDependency: layoutDependency,
                            layoutId: "VG0lWCO4J",
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector":
                                      "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial", monospace',
                                    "--framer-font-size": "12px",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children:
                                    "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                                }),
                              }),
                              className: "framer-1ihrxuw",
                              "data-framer-name": "Description",
                              fonts: ["GF;GT Flexa Mono Trial-regular"],
                              layoutDependency: layoutDependency,
                              layoutId: "y9YGh2ZgF",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64))",
                                "--framer-paragraph-spacing": "0px",
                              },
                              variants: {
                                UGRdVJ0L7: {
                                  "--extracted-r6o4lv":
                                    "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                                },
                              },
                              verticalAlignment: "center",
                              withExternalLayout: true,
                              ...addPropertyOverrides(
                                {
                                  UGRdVJ0L7: {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          style: {
                                            "--font-selector":
                                              "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                            "--framer-font-family":
                                              '"GT Flexa Mono Trial", monospace',
                                            "--framer-font-size": "12px",
                                            "--framer-line-height": "150%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                            "--framer-text-transform":
                                              "uppercase",
                                          },
                                          children:
                                            "Rather than locking you into an iron-clad year-long contract,\xa0 we ask our clients to commit to just 3-months at a time. We’re confident you’ll be so overwhelmed with the value we provide, you’ll want to re-up quarter after quarter after quarter.",
                                        }),
                                      }
                                    ),
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }),
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1docp58",
                      "data-border": true,
                      "data-framer-name": "HorizontalBorder",
                      layoutDependency: layoutDependency,
                      layoutId: "VJU7PhiAK",
                      style: {
                        "--border-bottom-width": "0px",
                        "--border-color": "rgb(34, 34, 34)",
                        "--border-left-width": "0px",
                        "--border-right-width": "0px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                      },
                    }),
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-12jtf9t",
                      "data-framer-name": "Step Indicator",
                      layoutDependency: layoutDependency,
                      layoutId: "TjCo_0ZoS",
                      children: [
                        isDisplayed() &&
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-4jmse6",
                            "data-framer-name": "Overlay",
                            layoutDependency: layoutDependency,
                            layoutId: "r13ZvtKnt",
                            style: {
                              backgroundColor: "rgba(61, 61, 61, 0.7)",
                              borderBottomLeftRadius: 999,
                              borderBottomRightRadius: 999,
                              borderTopLeftRadius: 999,
                              borderTopRightRadius: 999,
                            },
                          }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "12px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                              },
                              children: "03",
                            }),
                          }),
                          className: "framer-1rkco17",
                          "data-framer-name": "Step Number",
                          fonts: ["GF;Suisse Int'l-regular"],
                          layoutDependency: layoutDependency,
                          layoutId: "gcV17neI8",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                            "--framer-paragraph-spacing": "0px",
                          },
                          transformTemplate: transformTemplate2,
                          verticalAlignment: "center",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  ],
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ZFAOn.framer-y2c5zu, .framer-ZFAOn .framer-y2c5zu { display: block; }",
  ".framer-ZFAOn.framer-d57yq7 { cursor: pointer; gap: 24px; height: 324px; overflow: visible; position: relative; width: 1200px; }",
  ".framer-ZFAOn .framer-d3hr9n { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; top: 38px; width: 100%; }",
  ".framer-ZFAOn .framer-q5t0p9 { flex: none; height: 242px; overflow: visible; position: relative; width: 900px; }",
  ".framer-ZFAOn .framer-18110dc { align-content: center; align-items: center; bottom: 5px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 52%; overflow: hidden; padding: 0px; position: absolute; width: min-content; }",
  ".framer-ZFAOn .framer-dbrsu7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 473px; word-break: break-word; word-wrap: break-word; }",
  ".framer-ZFAOn .framer-egec4q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 52%; overflow: hidden; padding: 0px; position: absolute; top: 11px; width: min-content; }",
  ".framer-ZFAOn .framer-11461ds, .framer-ZFAOn .framer-4w46qo { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-ZFAOn .framer-1rk5woj { bottom: 0px; flex: none; height: 137px; left: calc(50.00000000000002% - 100% / 2); position: absolute; width: 100%; }",
  ".framer-ZFAOn .framer-1hcdmh { flex: none; height: 21px; left: 188px; overflow: visible; position: absolute; top: 0px; width: 21px; }",
  ".framer-ZFAOn .framer-1guuqyp { flex: none; height: auto; left: 52%; position: absolute; top: 52%; white-space: pre; width: auto; }",
  ".framer-ZFAOn .framer-160sxqb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; top: 50%; width: 390px; }",
  ".framer-ZFAOn .framer-zsauux { flex: none; gap: 24px; height: 234px; overflow: visible; position: relative; width: 335px; }",
  ".framer-ZFAOn .framer-151sbie { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 0px; width: min-content; }",
  ".framer-ZFAOn .framer-1y5sysx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ZFAOn .framer-15ofuo9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ZFAOn .framer-bimijk, .framer-ZFAOn .framer-10fkyir, .framer-ZFAOn .framer-a7289w { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-ZFAOn .framer-wifhv0 { align-content: center; align-items: center; bottom: 21px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; width: 100%; }",
  ".framer-ZFAOn .framer-44v6l1 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 24px 0px 24px; position: relative; width: 1px; }",
  ".framer-ZFAOn .framer-1ihrxuw { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-ZFAOn .framer-1docp58 { bottom: 0px; flex: none; height: 158px; left: calc(50.00000000000002% - 100% / 2); position: absolute; width: 100%; }",
  ".framer-ZFAOn .framer-12jtf9t { flex: none; height: 21px; left: calc(5.671641791044799% - 21px / 2); overflow: visible; position: absolute; top: calc(5.982905982906005% - 21px / 2); width: 21px; }",
  ".framer-ZFAOn .framer-4jmse6 { flex: none; height: 21px; left: calc(47.61904761904764% - 21px / 2); position: absolute; top: calc(47.61904761904764% - 21px / 2); width: 21px; }",
  ".framer-ZFAOn .framer-1rkco17 { flex: none; height: auto; left: 48%; position: absolute; top: 52%; white-space: pre; width: auto; }",
  ".framer-ZFAOn.framer-v-1wpmnmv.framer-d57yq7, .framer-ZFAOn.framer-v-1wpmnmv .framer-q5t0p9 { width: 810px; }",
  ".framer-ZFAOn.framer-v-1wpmnmv .framer-1rk5woj { left: calc(50.00000000000002% - 635px / 2); width: 635px; }",
  ".framer-ZFAOn.framer-v-1wpmnmv .framer-1hcdmh { left: calc(19.62962962962965% - 21px / 2); top: calc(4.1322314049587% - 21px / 2); }",
  ".framer-ZFAOn.framer-v-1wpmnmv .framer-1guuqyp { left: 1px; }",
  ".framer-ZFAOn.framer-v-1k8olky.framer-d57yq7, .framer-ZFAOn.framer-v-1pddxag.framer-d57yq7 { cursor: unset; width: 390px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd.framer-d57yq7 { width: 1512px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-d3hr9n { right: 0px; top: 49px; width: unset; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-q5t0p9 { height: 275px; width: 1512px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-18110dc { bottom: 64px; left: 50%; width: 100%; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-dbrsu7 { width: 1000px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-egec4q { left: 52%; top: 0px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-1rk5woj { height: 163px; left: calc(50.00000000000002% - 1200px / 2); width: 1200px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-1hcdmh { left: 500px; }",
  ".framer-ZFAOn.framer-v-1k3d7nd .framer-1guuqyp { left: 2px; }",
  ".framer-ZFAOn.framer-v-d57yq7.hover .framer-dbrsu7 { order: 0; }",
  ".framer-ZFAOn.framer-v-1k3d7nd.hover .framer-d3hr9n { width: unset; }",
  ".framer-ZFAOn.framer-v-1k3d7nd.hover .framer-1guuqyp { left: 48%; }",
  '.framer-ZFAOn[data-border="true"]::after, .framer-ZFAOn [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 324
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"WcR3QIn90":{"layout":["fixed","fixed"]},"N5hCQMb7r":{"layout":["fixed","fixed"]},"dPHUZjnq6":{"layout":["fixed","fixed"]},"UGRdVJ0L7":{"layout":["fixed","fixed"]},"py2PyXgcp":{"layout":["fixed","fixed"]},"SPLnPcwHT":{"layout":["fixed","fixed"]},"gyhTzK6ak":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramermVrDlTXcf = withCSS(Component, css, "framer-ZFAOn");
export default FramermVrDlTXcf;
FramermVrDlTXcf.displayName = "box-3";
FramermVrDlTXcf.defaultProps = { height: 324, width: 1200 };
addPropertyControls(FramermVrDlTXcf, {
  variant: {
    options: ["l8mCqTv73", "WcR3QIn90", "N5hCQMb7r", "dPHUZjnq6", "UGRdVJ0L7"],
    optionTitles: [
      "Variant 1",
      "Variant 2",
      "Variant 3",
      "Variant 4",
      "Variant 5",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramermVrDlTXcf, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramermVrDlTXcf",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicWidth: "1200",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"WcR3QIn90":{"layout":["fixed","fixed"]},"N5hCQMb7r":{"layout":["fixed","fixed"]},"dPHUZjnq6":{"layout":["fixed","fixed"]},"UGRdVJ0L7":{"layout":["fixed","fixed"]},"py2PyXgcp":{"layout":["fixed","fixed"]},"SPLnPcwHT":{"layout":["fixed","fixed"]},"gyhTzK6ak":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "324",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./mVrDlTXcf.map
