// Generated by Framer (fed3180)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = {
  I2Yi3iDda: { hover: true },
  nmHMAoiNU: { hover: true },
  Svis8cpkF: { hover: true },
};
const cycleOrder = [
  "I2Yi3iDda",
  "nmHMAoiNU",
  "Svis8cpkF",
  "WiDeAGnCp",
  "a_1MyMjNe",
];
const serializationHash = "framer-DwnWD";
const variantClassNames = {
  a_1MyMjNe: "framer-v-bcqf04",
  I2Yi3iDda: "framer-v-1qz2fqs",
  nmHMAoiNU: "framer-v-14hl9m8",
  Svis8cpkF: "framer-v-ddut4j",
  WiDeAGnCp: "framer-v-1p0g91b",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "I2Yi3iDda",
  "Variant 2": "nmHMAoiNU",
  "Variant 3": "Svis8cpkF",
  "Variant 4": "WiDeAGnCp",
  "Variant 5": "a_1MyMjNe",
};
const getProps = ({ click, height, id, width, ...props }) => {
  return {
    ...props,
    i6vlZsiGO: click ?? props.i6vlZsiGO,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "I2Yi3iDda",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, i6vlZsiGO, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "I2Yi3iDda",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap6ijgmt = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (i6vlZsiGO) {
      const res = await i6vlZsiGO(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1qz2fqs",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "I2Yi3iDda",
          onTap: onTap6ijgmt,
          ref: refBinding,
          style: {
            backgroundColor: "rgb(20, 20, 20)",
            borderBottomLeftRadius: 8,
            borderBottomRightRadius: 8,
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            ...style,
          },
          variants: {
            "I2Yi3iDda-hover": { backgroundColor: "rgb(31, 31, 31)" },
            "nmHMAoiNU-hover": { backgroundColor: "rgb(31, 31, 31)" },
            "Svis8cpkF-hover": { backgroundColor: "rgb(31, 31, 31)" },
            a_1MyMjNe: { backgroundColor: "rgb(31, 31, 31)" },
            WiDeAGnCp: { backgroundColor: "rgb(31, 31, 31)" },
          },
          ...addPropertyOverrides(
            {
              "I2Yi3iDda-hover": { "data-framer-name": undefined },
              "nmHMAoiNU-hover": { "data-framer-name": undefined },
              "Svis8cpkF-hover": { "data-framer-name": undefined },
              a_1MyMjNe: { "data-framer-name": "Variant 5" },
              nmHMAoiNU: { "data-framer-name": "Variant 2" },
              Svis8cpkF: { "data-framer-name": "Variant 3" },
              WiDeAGnCp: { "data-framer-name": "Variant 4" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-19c6ajp",
              "data-framer-name": "Ellipse 7",
              layoutDependency: layoutDependency,
              layoutId: "V7Zo9UfEg",
              style: {
                background:
                  "linear-gradient(270deg, rgba(255, 228, 53, 0.5) 0%, rgba(255, 193, 49, 0.5) 100%)",
                backgroundColor: "rgba(0, 0, 0, 0)",
                borderBottomLeftRadius: "100%",
                borderBottomRightRadius: "100%",
                borderTopLeftRadius: "100%",
                borderTopRightRadius: "100%",
              },
              variants: {
                "I2Yi3iDda-hover": {
                  background:
                    "linear-gradient(270deg, rgb(255, 221, 0) 0%, rgb(255, 221, 0) 100%)",
                  backgroundColor: "rgb(255, 221, 0)",
                },
                "nmHMAoiNU-hover": {
                  background:
                    "linear-gradient(270deg, rgb(255, 221, 0) 0%, rgb(255, 221, 0) 100%)",
                  backgroundColor: "rgb(255, 221, 0)",
                },
                "Svis8cpkF-hover": {
                  background:
                    "linear-gradient(270deg, rgb(255, 221, 0) 0%, rgb(255, 221, 0) 100%)",
                  backgroundColor: "rgb(255, 221, 0)",
                },
                a_1MyMjNe: {
                  background:
                    "linear-gradient(270deg, rgb(255, 221, 0) 0%, rgb(255, 221, 0) 100%)",
                  backgroundColor: "rgb(255, 221, 0)",
                },
                WiDeAGnCp: {
                  background:
                    "linear-gradient(270deg, rgb(255, 221, 0) 0%, rgb(255, 221, 0) 100%)",
                  backgroundColor: "rgb(255, 221, 0)",
                },
              },
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Geist", "Geist Placeholder", sans-serif',
                    "--framer-font-size": "14.6px",
                    "--framer-line-height": "19.47px",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(87, 87, 87))",
                  },
                  children: "Phase 02: The Silence",
                }),
              }),
              className: "framer-1fncjqr",
              "data-framer-name": "Phase 01: The Rendezvous",
              fonts: ["GF;Geist-regular"],
              layoutDependency: layoutDependency,
              layoutId: "oDRsKNYPe",
              style: {
                "--extracted-r6o4lv": "rgb(87, 87, 87)",
                "--framer-paragraph-spacing": "0px",
              },
              variants: {
                "I2Yi3iDda-hover": {
                  "--extracted-r6o4lv":
                    "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                },
                "nmHMAoiNU-hover": {
                  "--extracted-r6o4lv":
                    "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                },
                "Svis8cpkF-hover": {
                  "--extracted-r6o4lv":
                    "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                },
                a_1MyMjNe: {
                  "--extracted-r6o4lv":
                    "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                },
                WiDeAGnCp: {
                  "--extracted-r6o4lv":
                    "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                },
              },
              verticalAlignment: "center",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  "I2Yi3iDda-hover": {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "14.6px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                  "nmHMAoiNU-hover": {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "12px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                  "Svis8cpkF-hover": {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "15px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                  a_1MyMjNe: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "15px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                  nmHMAoiNU: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "12px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(87, 87, 87))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                  Svis8cpkF: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "15px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(87, 87, 87))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                  WiDeAGnCp: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "14.6px",
                          "--framer-line-height": "19.47px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                        },
                        children: "Phase 02: The Silence",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-DwnWD.framer-6ge2fo, .framer-DwnWD .framer-6ge2fo { display: block; }",
  ".framer-DwnWD.framer-1qz2fqs { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 12px 16px 12px; position: relative; width: 248px; }",
  ".framer-DwnWD .framer-19c6ajp { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 12px); position: relative; width: 12px; }",
  ".framer-DwnWD .framer-1fncjqr { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-DwnWD.framer-v-14hl9m8.framer-1qz2fqs { width: 145px; }",
  ".framer-DwnWD.framer-v-14hl9m8 .framer-1fncjqr, .framer-DwnWD.framer-v-ddut4j .framer-1fncjqr, .framer-DwnWD.framer-v-bcqf04 .framer-1fncjqr { flex: 1 0 0px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-DwnWD.framer-v-ddut4j.framer-1qz2fqs, .framer-DwnWD.framer-v-bcqf04.framer-1qz2fqs { width: 160px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 51
 * @framerIntrinsicWidth 248
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"nmHMAoiNU":{"layout":["fixed","auto"]},"Svis8cpkF":{"layout":["fixed","auto"]},"WiDeAGnCp":{"layout":["fixed","auto"]},"a_1MyMjNe":{"layout":["fixed","auto"]},"nK0gugVCl":{"layout":["fixed","auto"]},"o2xuAUzRO":{"layout":["fixed","auto"]},"Cw6UETX_E":{"layout":["fixed","auto"]}}}
 * @framerVariables {"i6vlZsiGO":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameruSQKcGJsm = withCSS(Component, css, "framer-DwnWD");
export default FrameruSQKcGJsm;
FrameruSQKcGJsm.displayName = "Phase 2";
FrameruSQKcGJsm.defaultProps = { height: 51, width: 248 };
addPropertyControls(FrameruSQKcGJsm, {
  variant: {
    options: ["I2Yi3iDda", "nmHMAoiNU", "Svis8cpkF", "WiDeAGnCp", "a_1MyMjNe"],
    optionTitles: [
      "Variant 1",
      "Variant 2",
      "Variant 3",
      "Variant 4",
      "Variant 5",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  i6vlZsiGO: { title: "Click", type: ControlType.EventHandler },
});
addFonts(
  FrameruSQKcGJsm,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Geist",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameruSQKcGJsm",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "248",
        framerIntrinsicHeight: "51",
        framerImmutableVariables: "true",
        framerVariables: '{"i6vlZsiGO":"click"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"nmHMAoiNU":{"layout":["fixed","auto"]},"Svis8cpkF":{"layout":["fixed","auto"]},"WiDeAGnCp":{"layout":["fixed","auto"]},"a_1MyMjNe":{"layout":["fixed","auto"]},"nK0gugVCl":{"layout":["fixed","auto"]},"o2xuAUzRO":{"layout":["fixed","auto"]},"Cw6UETX_E":{"layout":["fixed","auto"]}}}',
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerColorSyntax: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./uSQKcGJsm.map
