// Generated by Framer (a1ad18b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = {
  tkV1qLpyx: { hover: true },
  tplFWOnE1: { hover: true },
  vaiBPi28W: { hover: true },
};
const cycleOrder = [
  "vaiBPi28W",
  "tplFWOnE1",
  "SX2zCl3oN",
  "tkV1qLpyx",
  "UCLr1bS_p",
];
const serializationHash = "framer-Tss2l";
const variantClassNames = {
  SX2zCl3oN: "framer-v-13vzl8v",
  tkV1qLpyx: "framer-v-1lifdpw",
  tplFWOnE1: "framer-v-uxvi56",
  UCLr1bS_p: "framer-v-2q6ywh",
  vaiBPi28W: "framer-v-x2j4f5",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "vaiBPi28W",
  "Variant 2": "tplFWOnE1",
  "Variant 3": "SX2zCl3oN",
  "Variant 4": "tkV1qLpyx",
  "Variant 5": "UCLr1bS_p",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "vaiBPi28W",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "vaiBPi28W",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-x2j4f5",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "vaiBPi28W",
          ref: refBinding,
          style: {
            backgroundColor: "rgba(0, 0, 0, 0)",
            boxShadow: "none",
            ...style,
          },
          variants: {
            "tkV1qLpyx-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow:
                "inset 0px 4px 4px 0px rgb(255, 76, 36), 0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            "tplFWOnE1-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow:
                "inset 0px 4px 4px 0px rgb(255, 76, 36), 0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            "vaiBPi28W-hover": {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow:
                "inset 0px 4px 4px 0px rgb(244, 72, 73), 0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
            UCLr1bS_p: {
              backgroundColor:
                "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
              boxShadow: "0px 0px 80px 45px rgba(255, 76, 36, 0.32)",
            },
          },
          ...addPropertyOverrides(
            {
              "tkV1qLpyx-hover": { "data-framer-name": undefined },
              "tplFWOnE1-hover": { "data-framer-name": undefined },
              "vaiBPi28W-hover": { "data-framer-name": undefined },
              SX2zCl3oN: { "data-framer-name": "Variant 3" },
              tkV1qLpyx: { "data-framer-name": "Variant 4" },
              tplFWOnE1: { "data-framer-name": "Variant 2" },
              UCLr1bS_p: { "data-framer-name": "Variant 5" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(motion.div, {
            className: "framer-p3mqnj",
            "data-framer-name": "One Problem",
            layoutDependency: layoutDependency,
            layoutId: "XAcoRQfL7",
            children: /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-m0s36r",
              "data-framer-name": "One Problem",
              layoutDependency: layoutDependency,
              layoutId: "mhk6YiNW4",
              children: [
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-angrpi",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "USlbBtmr7",
                  transformTemplate: transformTemplate1,
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-w1tq39",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "LOdqLAPS6",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1l6b8xc",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "DCjzVfdLA",
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1dajoqd",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "pq1UcxdVR",
                        children: /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h3, {
                              dir: "auto",
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "88px",
                                "--framer-letter-spacing": "-4px",
                                "--framer-line-height": "76px",
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--extracted-a0htzi, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                              },
                              children: "One Problem",
                            }),
                          }),
                          className: "framer-5z8hzx",
                          "data-framer-name": "Step Title",
                          fonts: ["GF;Suisse Int'l-regular"],
                          layoutDependency: layoutDependency,
                          layoutId: "cEzBAvc5B",
                          style: {
                            "--extracted-a0htzi":
                              "var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61))",
                            "--framer-paragraph-spacing": "0px",
                          },
                          variants: {
                            "tkV1qLpyx-hover": {
                              "--extracted-a0htzi":
                                "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                            },
                            "tplFWOnE1-hover": {
                              "--extracted-a0htzi":
                                "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                            },
                            "vaiBPi28W-hover": {
                              "--extracted-a0htzi":
                                "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                            },
                            UCLr1bS_p: {
                              "--extracted-a0htzi":
                                "var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21))",
                            },
                          },
                          verticalAlignment: "center",
                          withExternalLayout: true,
                          ...addPropertyOverrides(
                            {
                              "tkV1qLpyx-hover": {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h3, {
                                    dir: "auto",
                                    style: {
                                      "--font-selector":
                                        "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                      "--framer-font-size": "88px",
                                      "--framer-letter-spacing": "-4px",
                                      "--framer-line-height": "76px",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                    },
                                    children: "One Problem",
                                  }),
                                }),
                              },
                              "tplFWOnE1-hover": {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h3, {
                                    dir: "auto",
                                    style: {
                                      "--font-selector":
                                        "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                      "--framer-font-size": "88px",
                                      "--framer-letter-spacing": "-4px",
                                      "--framer-line-height": "76px",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                    },
                                    children: "One Problem",
                                  }),
                                }),
                              },
                              "vaiBPi28W-hover": {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h3, {
                                    dir: "auto",
                                    style: {
                                      "--font-selector":
                                        "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                      "--framer-font-size": "88px",
                                      "--framer-letter-spacing": "-4px",
                                      "--framer-line-height": "76px",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                    },
                                    children: "One Problem",
                                  }),
                                }),
                              },
                              SX2zCl3oN: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h3, {
                                    dir: "auto",
                                    style: {
                                      "--font-selector":
                                        "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                      "--framer-font-size": "50px",
                                      "--framer-letter-spacing": "-4px",
                                      "--framer-line-height": "76px",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-a0htzi, var(--token-6e0590d2-2716-47b0-9c95-9127ea7d3293, rgb(61, 61, 61)))",
                                    },
                                    children: "One Problem",
                                  }),
                                }),
                              },
                              UCLr1bS_p: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h3, {
                                    dir: "auto",
                                    style: {
                                      "--font-selector":
                                        "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                      "--framer-font-size": "50px",
                                      "--framer-letter-spacing": "-4px",
                                      "--framer-line-height": "76px",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-a0htzi, var(--token-0eb7ea63-0542-4617-8b33-b2f98bdd4cde, rgb(21, 21, 21)))",
                                    },
                                    children: "One Problem",
                                  }),
                                }),
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      }),
                    }),
                  }),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1fw1wqe",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "Ku_iI5xHY",
                  transformTemplate: transformTemplate1,
                  ...addPropertyOverrides(
                    {
                      SX2zCl3oN: { transformTemplate: undefined },
                      UCLr1bS_p: { transformTemplate: undefined },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1u0f4ui",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "hrE8DnK0j",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1br9mz0",
                      "data-framer-name": "Container",
                      layoutDependency: layoutDependency,
                      layoutId: "o4KT6whRn",
                      style: { opacity: 0.7 },
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1ru3bpx",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "YeMw24SQj",
                        children: /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                "--framer-font-family":
                                  '"GT Flexa Mono Trial", monospace',
                                "--framer-font-size": "14px",
                                "--framer-line-height": "150%",
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children:
                                "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                            }),
                          }),
                          className: "framer-1j4ylf0",
                          "data-framer-name": "Description",
                          fonts: ["GF;GT Flexa Mono Trial-regular"],
                          layoutDependency: layoutDependency,
                          layoutId: "GIWnZwjXV",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64))",
                            "--framer-paragraph-spacing": "0px",
                          },
                          variants: {
                            "tkV1qLpyx-hover": {
                              "--extracted-r6o4lv":
                                "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                            },
                            "tplFWOnE1-hover": {
                              "--extracted-r6o4lv":
                                "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                            },
                            "vaiBPi28W-hover": {
                              "--extracted-r6o4lv":
                                "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                            },
                            UCLr1bS_p: {
                              "--extracted-r6o4lv":
                                "var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21))",
                            },
                          },
                          verticalAlignment: "center",
                          withExternalLayout: true,
                          ...addPropertyOverrides(
                            {
                              "tkV1qLpyx-hover": {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                      "--framer-font-family":
                                        '"GT Flexa Mono Trial", monospace',
                                      "--framer-line-height": "150%",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                      "--framer-text-transform": "uppercase",
                                    },
                                    children:
                                      "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                  }),
                                }),
                              },
                              "tplFWOnE1-hover": {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                      "--framer-font-family":
                                        '"GT Flexa Mono Trial", monospace',
                                      "--framer-font-size": "14px",
                                      "--framer-line-height": "150%",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                      "--framer-text-transform": "uppercase",
                                    },
                                    children:
                                      "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                  }),
                                }),
                              },
                              "vaiBPi28W-hover": {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                      "--framer-font-family":
                                        '"GT Flexa Mono Trial", monospace',
                                      "--framer-font-size": "14px",
                                      "--framer-line-height": "150%",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                      "--framer-text-transform": "uppercase",
                                    },
                                    children:
                                      "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                  }),
                                }),
                              },
                              SX2zCl3oN: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                      "--framer-font-family":
                                        '"GT Flexa Mono Trial", monospace',
                                      "--framer-font-size": "12px",
                                      "--framer-line-height": "150%",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                      "--framer-text-transform": "uppercase",
                                    },
                                    children:
                                      "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                  }),
                                }),
                              },
                              tkV1qLpyx: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                      "--framer-font-family":
                                        '"GT Flexa Mono Trial", monospace',
                                      "--framer-line-height": "150%",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-b5d5ba65-e53c-4e5f-9d6b-02f0eed40135, rgb(65, 64, 64)))",
                                      "--framer-text-transform": "uppercase",
                                    },
                                    children:
                                      "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                  }),
                                }),
                              },
                              UCLr1bS_p: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector":
                                        "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                      "--framer-font-family":
                                        '"GT Flexa Mono Trial", monospace',
                                      "--framer-font-size": "12px",
                                      "--framer-line-height": "150%",
                                      "--framer-text-alignment": "center",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0d9f8c38-44ad-488f-bd46-40d1aae2e71a, rgb(21, 21, 21)))",
                                      "--framer-text-transform": "uppercase",
                                    },
                                    children:
                                      "We don’t solve problems. We overwhelm them. We focus on the biggest baddest wolf plaguing your enterprise and we throw all of our resources, expertise and creative powers at taking it down.",
                                  }),
                                }),
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      }),
                    }),
                  }),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-vjqt2c",
                  "data-border": true,
                  "data-framer-name": "HorizontalBorder",
                  layoutDependency: layoutDependency,
                  layoutId: "LNTrlBfIB",
                  style: {
                    "--border-bottom-width": "0px",
                    "--border-color": "rgb(34, 34, 34)",
                    "--border-left-width": "0px",
                    "--border-right-width": "0px",
                    "--border-style": "solid",
                    "--border-top-width": "1px",
                  },
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1jbcvqs",
                  "data-framer-name": "Step Indicator",
                  layoutDependency: layoutDependency,
                  layoutId: "CIrM8MYCG",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                          "--framer-font-family":
                            '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                          "--framer-font-size": "12px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "12px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                        },
                        children: "01",
                      }),
                    }),
                    className: "framer-18xlvzz",
                    "data-framer-name": "Step Number",
                    fonts: ["GF;Suisse Int'l-regular"],
                    layoutDependency: layoutDependency,
                    layoutId: "MFJXKb9i7",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    transformTemplate: transformTemplate2,
                    variants: {
                      "tkV1qLpyx-hover": {
                        "--extracted-r6o4lv":
                          "var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0))",
                      },
                      "tplFWOnE1-hover": {
                        "--extracted-r6o4lv": "rgb(21, 21, 21)",
                      },
                      "vaiBPi28W-hover": {
                        "--extracted-r6o4lv": "rgb(21, 21, 21)",
                      },
                    },
                    verticalAlignment: "center",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        "tkV1qLpyx-hover": {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "12px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-2ede4937-6b1c-4e97-9e3f-88a20c81ea72, rgb(0, 0, 0)))",
                              },
                              children: "01",
                            }),
                          }),
                        },
                        "tplFWOnE1-hover": {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "12px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(21, 21, 21))",
                              },
                              children: "01",
                            }),
                          }),
                        },
                        "vaiBPi28W-hover": {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "12px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(21, 21, 21))",
                              },
                              children: "01",
                            }),
                          }),
                        },
                        SX2zCl3oN: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "9px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                              },
                              children: "01",
                            }),
                          }),
                        },
                        tkV1qLpyx: { transformTemplate: transformTemplate1 },
                        UCLr1bS_p: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                "--framer-font-family":
                                  '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                "--framer-font-size": "9px",
                                "--framer-letter-spacing": "0px",
                                "--framer-line-height": "12px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                              },
                              children: "01",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              ],
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Tss2l.framer-2t75nh, .framer-Tss2l .framer-2t75nh { display: block; }",
  ".framer-Tss2l.framer-x2j4f5 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 323px; justify-content: center; padding: 0px; position: relative; width: 1200px; }",
  ".framer-Tss2l .framer-p3mqnj { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-Tss2l .framer-m0s36r { flex: none; gap: 24px; height: 212px; overflow: visible; position: relative; width: 1200px; }",
  ".framer-Tss2l .framer-angrpi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 0px; width: min-content; }",
  ".framer-Tss2l .framer-w1tq39 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-Tss2l .framer-1l6b8xc, .framer-Tss2l .framer-1br9mz0, .framer-Tss2l .framer-1ru3bpx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-Tss2l .framer-1dajoqd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Tss2l .framer-5z8hzx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Tss2l .framer-1fw1wqe { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 117px; width: 521px; }",
  ".framer-Tss2l .framer-1u0f4ui { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 10px 24px 10px 24px; position: relative; width: min-content; }",
  ".framer-Tss2l .framer-1j4ylf0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 473px; word-break: break-word; word-wrap: break-word; }",
  ".framer-Tss2l .framer-vjqt2c { bottom: 6px; flex: none; left: calc(49.9762273656735% - 914px / 2); position: absolute; top: 108px; width: 914px; }",
  ".framer-Tss2l .framer-1jbcvqs { flex: none; height: 21px; left: calc(29.16666666666669% - 21px / 2); overflow: visible; position: absolute; top: calc(8.018867924528324% - 21px / 2); width: 21px; }",
  ".framer-Tss2l .framer-18xlvzz { flex: none; height: auto; left: 48%; position: absolute; top: 52%; white-space: pre; width: auto; }",
  ".framer-Tss2l.framer-v-uxvi56.framer-x2j4f5 { width: 810px; }",
  ".framer-Tss2l.framer-v-uxvi56 .framer-m0s36r { height: 221px; width: 810px; }",
  ".framer-Tss2l.framer-v-uxvi56 .framer-angrpi { left: 50%; top: 7px; }",
  ".framer-Tss2l.framer-v-uxvi56 .framer-1dajoqd { order: 0; }",
  ".framer-Tss2l.framer-v-uxvi56 .framer-vjqt2c { left: 88px; right: 87px; width: unset; }",
  ".framer-Tss2l.framer-v-uxvi56 .framer-1jbcvqs { left: calc(19.876543209876566% - 21px / 2); top: calc(5.429864253393688% - 21px / 2); }",
  ".framer-Tss2l.framer-v-13vzl8v.framer-x2j4f5, .framer-Tss2l.framer-v-2q6ywh.framer-x2j4f5 { cursor: unset; padding: 0px 16px 0px 16px; width: 390px; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-p3mqnj, .framer-Tss2l.framer-v-2q6ywh .framer-p3mqnj { flex: none; width: 390px; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-m0s36r, .framer-Tss2l.framer-v-1lifdpw .framer-m0s36r, .framer-Tss2l.framer-v-2q6ywh .framer-m0s36r { flex: 1 0 0px; width: 1px; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-1fw1wqe, .framer-Tss2l.framer-v-2q6ywh .framer-1fw1wqe { bottom: 21px; justify-content: center; left: 0px; top: unset; width: 100%; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-1u0f4ui, .framer-Tss2l.framer-v-2q6ywh .framer-1u0f4ui { flex: 1 0 0px; padding: 0px 24px 0px 24px; width: 1px; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-1br9mz0, .framer-Tss2l.framer-v-13vzl8v .framer-1ru3bpx, .framer-Tss2l.framer-v-13vzl8v .framer-1j4ylf0, .framer-Tss2l.framer-v-2q6ywh .framer-1br9mz0, .framer-Tss2l.framer-v-2q6ywh .framer-1ru3bpx, .framer-Tss2l.framer-v-2q6ywh .framer-1j4ylf0 { width: 100%; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-vjqt2c, .framer-Tss2l.framer-v-2q6ywh .framer-vjqt2c { bottom: 0px; height: 127px; left: 32px; top: unset; width: 325px; }",
  ".framer-Tss2l.framer-v-13vzl8v .framer-1jbcvqs, .framer-Tss2l.framer-v-2q6ywh .framer-1jbcvqs { left: calc(14.35897435897438% - 21px / 2); top: calc(8.962264150943417% - 21px / 2); }",
  ".framer-Tss2l.framer-v-1lifdpw.framer-x2j4f5 { width: 1512px; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-p3mqnj { max-width: 100%; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-1fw1wqe { bottom: -9px; left: 50%; top: unset; width: 100%; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-1u0f4ui { align-content: center; align-items: center; flex: 1 0 0px; width: 1px; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-1br9mz0 { align-content: center; align-items: center; justify-content: center; width: 100%; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-1ru3bpx { align-content: center; align-items: center; justify-content: center; width: 1036px; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-1j4ylf0 { height: 109px; width: 1022px; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-vjqt2c { bottom: 8px; height: 98px; left: 156px; right: 156px; top: unset; width: unset; }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-1jbcvqs { left: calc(32.870370370370395% - 21px / 2); top: calc(7.07547169811323% - 21px / 2); }",
  ".framer-Tss2l.framer-v-1lifdpw .framer-18xlvzz { bottom: 4px; left: 52%; top: unset; }",
  ".framer-Tss2l.framer-v-uxvi56.hover .framer-vjqt2c { width: unset; }",
  ".framer-Tss2l.framer-v-1lifdpw.hover .framer-1fw1wqe, .framer-Tss2l.framer-v-1lifdpw.hover .framer-18xlvzz { top: unset; }",
  ".framer-Tss2l.framer-v-1lifdpw.hover .framer-vjqt2c { top: unset; width: unset; }",
  '.framer-Tss2l[data-border="true"]::after, .framer-Tss2l [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 323
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"tplFWOnE1":{"layout":["fixed","fixed"]},"SX2zCl3oN":{"layout":["fixed","fixed"]},"tkV1qLpyx":{"layout":["fixed","fixed"]},"UCLr1bS_p":{"layout":["fixed","fixed"]},"hBsnuQADz":{"layout":["fixed","fixed"]},"PstRZxClD":{"layout":["fixed","fixed"]},"ZaaNUbDDA":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameraqY6s5mxf = withCSS(Component, css, "framer-Tss2l");
export default FrameraqY6s5mxf;
FrameraqY6s5mxf.displayName = "box-hover 2";
FrameraqY6s5mxf.defaultProps = { height: 323, width: 1200 };
addPropertyControls(FrameraqY6s5mxf, {
  variant: {
    options: ["vaiBPi28W", "tplFWOnE1", "SX2zCl3oN", "tkV1qLpyx", "UCLr1bS_p"],
    optionTitles: [
      "Variant 1",
      "Variant 2",
      "Variant 3",
      "Variant 4",
      "Variant 5",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FrameraqY6s5mxf, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FrameraqY6s5mxf",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerIntrinsicWidth: "1200",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerIntrinsicHeight: "323",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"tplFWOnE1":{"layout":["fixed","fixed"]},"SX2zCl3oN":{"layout":["fixed","fixed"]},"tkV1qLpyx":{"layout":["fixed","fixed"]},"UCLr1bS_p":{"layout":["fixed","fixed"]},"hBsnuQADz":{"layout":["fixed","fixed"]},"PstRZxClD":{"layout":["fixed","fixed"]},"ZaaNUbDDA":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./aqY6s5mxf.map
