// Generated by Framer (a1ad18b)
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "2cfs5v", mediaQuery: "(min-width: 1440px)" },
      {
        hash: "4slc3c",
        mediaQuery: "(min-width: 1026px) and (max-width: 1439.98px)",
      },
      {
        hash: "gl6pax",
        mediaQuery: "(min-width: 810px) and (max-width: 1025.98px)",
      },
      { hash: "rgyxx4", mediaQuery: "(max-width: 809.98px)" },
    ],
    description:
      "Honey is a hyper-nimble, fully-embedded design and growth wing that challenges enterprises to build, market and innovate at the speed and tenacity of a startup.",
    elements: {
      a2iFih0Hs: "start-here",
      bVyd7J0ZA: "useless-processes-wasteful-spend",
      bY5SPc4L4: "strategy",
      ClXlzT6bf: "promising-start-1",
      GpqBxcmtV: "017",
      HbSs7NRWP: "promising-start-3",
      ht9uQx9pR: "post-contract-reality",
      KTVkFoRdD: "two-weeks",
      MDqIQqF0s: "web-design",
      N8FbwwHtD: "promising-start-2",
      O1L1FJs_E: "campaigns",
      oJcpkhrJJ: "branding",
      OO6cK3zTe: "after-honey",
      qLYx8UnQi: "011",
      RAcrC0RzY: "promising-start",
      RWZe0QdQQ: "ui-ux",
      sA6wYDPsZ: "008",
      SiXJcIbgV: "art-direction",
      WIaf5Dqvo: "three-months",
      XH3GOt6FK: "one-problem",
      xhd4KNap6: "003",
      xwQbSVztf: "rules",
      Ypd9rrBcR: "left",
      zahGL9L77: "copywriting",
      Zw81KtK5m: "video",
    },
    framerSearch: { index: true },
    robots: "max-image-preview:large",
    serializationId: "framer-8fj3A",
    title: "Honey",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
