// Generated by Framer (81bb052)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["aT2R_5V6q", "o6bSAMHHx"];
const serializationHash = "framer-6ofTV";
const variantClassNames = {
  aT2R_5V6q: "framer-v-n7d8qd",
  o6bSAMHHx: "framer-v-155mkv3",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const transition2 = { duration: 0, type: "tween" };
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Hide: "aT2R_5V6q", Show: "o6bSAMHHx" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "aT2R_5V6q",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "aT2R_5V6q",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppearno4dxg = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("o6bSAMHHx"), 10);
  });
  useOnVariantChange(baseVariant, { default: onAppearno4dxg });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "o6bSAMHHx") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "o6bSAMHHx") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          { o6bSAMHHx: { value: transition2 } },
          baseVariant,
          gestureVariant
        ),
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-n7d8qd",
            className,
            classNames
          ),
          "data-framer-name": "Hide",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "aT2R_5V6q",
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 17,
            borderBottomRightRadius: 17,
            borderTopLeftRadius: 17,
            borderTopRightRadius: 17,
            ...style,
          },
          ...addPropertyOverrides(
            { o6bSAMHHx: { "data-framer-name": "Show" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1c2qx8q",
            "data-framer-name": "Image Wrap",
            layoutDependency: layoutDependency,
            layoutId: "djHUEN6Ol",
            children: [
              isDisplayed() &&
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 7200,
                    intrinsicWidth: 5760,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0
                    ),
                    pixelHeight: 7200,
                    pixelWidth: 5760,
                    sizes: "191px",
                    src: "https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg",
                    srcSet:
                      "https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=1024 819w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=2048 1638w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=4096 3276w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg 5760w",
                  },
                  className: "framer-1cqd0su",
                  "data-framer-name": "Image",
                  layoutDependency: layoutDependency,
                  layoutId: "bA5sTvMSR",
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsxs(React.Fragment, {
                    children: [
                      /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                          "--framer-font-family":
                            '"GT Flexa Mono Trial", monospace',
                          "--framer-font-size": "10px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(149, 148, 148))",
                        },
                        children: "ANA WINTOUR ",
                      }),
                      /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                          "--framer-font-family":
                            '"GT Flexa Mono Trial", monospace',
                          "--framer-font-size": "10px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-2gxw0f, rgb(149, 148, 148))",
                        },
                        children: "// (1949–)",
                      }),
                    ],
                  }),
                  className: "framer-1mofrss",
                  fonts: ["GF;GT Flexa Mono Trial-regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "h6eCZLOE_",
                  style: {
                    "--extracted-2gxw0f": "rgb(149, 148, 148)",
                    "--extracted-r6o4lv": "rgb(149, 148, 148)",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  transformTemplate: transformTemplate1,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    pixelHeight: 293,
                    pixelWidth: 433,
                    positionX: "center",
                    positionY: "center",
                    src: "https://framerusercontent.com/images/2jO9ObvwAbwCP3CKyf1J9Jhg.jpg",
                  },
                  className: "framer-smkuj9",
                  "data-border": true,
                  layoutDependency: layoutDependency,
                  layoutId: "nJ5SXtaZZ",
                  style: {
                    "--border-bottom-width": "0.5px",
                    "--border-color": "rgb(34, 34, 34)",
                    "--border-left-width": "0.5px",
                    "--border-right-width": "0.5px",
                    "--border-style": "solid",
                    "--border-top-width": "0.5px",
                    borderBottomLeftRadius: 4,
                    borderBottomRightRadius: 4,
                    borderTopLeftRadius: 4,
                    borderTopRightRadius: 4,
                    boxShadow: "0px 4px 20px 0px rgba(255, 56, 56, 0.2)",
                    rotate: 9.14,
                  },
                  ...addPropertyOverrides(
                    {
                      o6bSAMHHx: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 143) - 0) *
                                0.5034965034965038 -
                                64)
                          ),
                          pixelHeight: 293,
                          pixelWidth: 433,
                          positionX: "center",
                          positionY: "center",
                          src: "https://framerusercontent.com/images/2jO9ObvwAbwCP3CKyf1J9Jhg.jpg",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-6ofTV.framer-h0yc5f, .framer-6ofTV .framer-h0yc5f { display: block; }",
  ".framer-6ofTV.framer-n7d8qd { height: 220px; overflow: hidden; position: relative; width: 178px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-6ofTV .framer-1c2qx8q { bottom: 220px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
  ".framer-6ofTV .framer-1cqd0su { flex: none; height: 224px; left: calc(50.00000000000002% - 191px / 2); overflow: visible; position: absolute; top: 0px; width: 191px; }",
  ".framer-6ofTV .framer-1mofrss { flex: none; height: auto; position: absolute; right: 3px; top: 54%; white-space: pre; width: auto; }",
  ".framer-6ofTV .framer-smkuj9 { flex: none; height: 128px; left: 12px; position: absolute; top: calc(50.349650349650375% - 128px / 2); width: 91px; z-index: 1; }",
  ".framer-6ofTV.framer-v-155mkv3.framer-n7d8qd { height: 143px; width: 225px; }",
  ".framer-6ofTV.framer-v-155mkv3 .framer-1c2qx8q { bottom: 0px; }",
  '.framer-6ofTV[data-border="true"]::after, .framer-6ofTV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 220
 * @framerIntrinsicWidth 178
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"o6bSAMHHx":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramercE9pNKFwy = withCSS(Component, css, "framer-6ofTV");
export default FramercE9pNKFwy;
FramercE9pNKFwy.displayName = "Image 16";
FramercE9pNKFwy.defaultProps = { height: 220, width: 178 };
addPropertyControls(FramercE9pNKFwy, {
  variant: {
    options: ["aT2R_5V6q", "o6bSAMHHx"],
    optionTitles: ["Hide", "Show"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramercE9pNKFwy, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramercE9pNKFwy",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"o6bSAMHHx":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "220",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "178",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./cE9pNKFwy.map
