// Generated by Framer (2ac8f15)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["tnTO96yNK", "ucnq_bol5"];
const serializationHash = "framer-pglgk";
const variantClassNames = {
  tnTO96yNK: "framer-v-ct8ngx",
  ucnq_bol5: "framer-v-s0tqyk",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const transition2 = { duration: 0, type: "tween" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Hide: "tnTO96yNK", Show: "ucnq_bol5" };
const getProps = ({ click, height, id, width, ...props }) => {
  return {
    ...props,
    kL7AaSDtq: click ?? props.kL7AaSDtq,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "tnTO96yNK",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, kL7AaSDtq, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "tnTO96yNK",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1ag6m75 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (kL7AaSDtq) {
      const res = await kL7AaSDtq(...args);
      if (res === false) return false;
    }
  });
  const onAppear1ilsjdq = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("ucnq_bol5"), 10);
  });
  useOnVariantChange(baseVariant, { default: onAppear1ilsjdq });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "ucnq_bol5") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "ucnq_bol5") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          { ucnq_bol5: { value: transition2 } },
          baseVariant,
          gestureVariant
        ),
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-ct8ngx",
            className,
            classNames
          ),
          "data-framer-name": "Hide",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "tnTO96yNK",
          onTap: onTap1ag6m75,
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 17,
            borderBottomRightRadius: 17,
            borderTopLeftRadius: 17,
            borderTopRightRadius: 17,
            ...style,
          },
          ...addPropertyOverrides(
            { ucnq_bol5: { "data-framer-name": "Show" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1g1hg15",
            "data-framer-name": "Image Wrap",
            layoutDependency: layoutDependency,
            layoutId: "XREzIRGUI",
            children: [
              isDisplayed() &&
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 7200,
                    intrinsicWidth: 5760,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0
                    ),
                    pixelHeight: 7200,
                    pixelWidth: 5760,
                    sizes: "191px",
                    src: "https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg",
                    srcSet:
                      "https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=1024 819w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=2048 1638w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg?scale-down-to=4096 3276w,https://framerusercontent.com/images/5AyA2cfwsRuyIP8JhLZ5Gakbfg.jpg 5760w",
                  },
                  className: "framer-16gd6mz",
                  "data-framer-name": "Image",
                  layoutDependency: layoutDependency,
                  layoutId: "aWsP9U9Ne",
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsxs(React.Fragment, {
                    children: [
                      /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                          "--framer-font-family":
                            '"GT Flexa Mono Trial", monospace',
                          "--framer-font-size": "10px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(149, 148, 148))",
                        },
                        children: "PABLO PICASSO ",
                      }),
                      /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                          "--framer-font-family":
                            '"GT Flexa Mono Trial", monospace',
                          "--framer-font-size": "10px",
                          "--framer-letter-spacing": "0px",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-2gxw0f, rgb(149, 148, 148))",
                        },
                        children: "// (1881-1973)",
                      }),
                    ],
                  }),
                  className: "framer-sv8a2f",
                  fonts: ["GF;GT Flexa Mono Trial-regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "iFNEQO8GD",
                  style: {
                    "--extracted-2gxw0f": "rgb(149, 148, 148)",
                    "--extracted-r6o4lv": "rgb(149, 148, 148)",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                    rotate: -7.7,
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    pixelHeight: 193,
                    pixelWidth: 259,
                    src: "https://framerusercontent.com/images/PdhHvVIaiw8QH5Ph0VHXSPGpBo.jpg",
                  },
                  className: "framer-9ydf11",
                  "data-border": true,
                  layoutDependency: layoutDependency,
                  layoutId: "okpamMZfW",
                  style: {
                    "--border-bottom-width": "0.5px",
                    "--border-color": "rgb(34, 34, 34)",
                    "--border-left-width": "0.5px",
                    "--border-right-width": "0.5px",
                    "--border-style": "solid",
                    "--border-top-width": "0.5px",
                    borderBottomLeftRadius: 4,
                    borderBottomRightRadius: 4,
                    borderTopLeftRadius: 4,
                    borderTopRightRadius: 4,
                    boxShadow: "0px 4px 20px 0px rgba(255, 56, 56, 0.2)",
                    rotate: -9.14,
                  },
                  ...addPropertyOverrides(
                    {
                      ucnq_bol5: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 157) - 0) *
                                0.541935483870968 -
                                64)
                          ),
                          pixelHeight: 193,
                          pixelWidth: 259,
                          src: "https://framerusercontent.com/images/PdhHvVIaiw8QH5Ph0VHXSPGpBo.jpg",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-pglgk.framer-1wk6btc, .framer-pglgk .framer-1wk6btc { display: block; }",
  ".framer-pglgk.framer-ct8ngx { cursor: pointer; height: 220px; overflow: hidden; position: relative; width: 178px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-pglgk .framer-1g1hg15 { bottom: 220px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
  ".framer-pglgk .framer-16gd6mz { flex: none; height: 224px; left: calc(50.00000000000002% - 191px / 2); overflow: visible; position: absolute; top: 0px; width: 191px; }",
  ".framer-pglgk .framer-sv8a2f { flex: none; height: auto; position: absolute; right: 2px; top: 8px; white-space: pre-wrap; width: 119px; word-break: break-word; word-wrap: break-word; }",
  ".framer-pglgk .framer-9ydf11 { flex: none; height: 128px; left: 10px; position: absolute; top: calc(54.193548387096804% - 128px / 2); width: 91px; z-index: 1; }",
  ".framer-pglgk.framer-v-s0tqyk.framer-ct8ngx { height: 157px; width: 223px; }",
  ".framer-pglgk.framer-v-s0tqyk .framer-1g1hg15 { bottom: 0px; }",
  '.framer-pglgk[data-border="true"]::after, .framer-pglgk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 220
 * @framerIntrinsicWidth 178
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ucnq_bol5":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"kL7AaSDtq":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerwy75ZqvAY = withCSS(Component, css, "framer-pglgk");
export default Framerwy75ZqvAY;
Framerwy75ZqvAY.displayName = "Image";
Framerwy75ZqvAY.defaultProps = { height: 220, width: 178 };
addPropertyControls(Framerwy75ZqvAY, {
  variant: {
    options: ["tnTO96yNK", "ucnq_bol5"],
    optionTitles: ["Hide", "Show"],
    title: "Variant",
    type: ControlType.Enum,
  },
  kL7AaSDtq: { title: "Click", type: ControlType.EventHandler },
});
addFonts(Framerwy75ZqvAY, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerwy75ZqvAY",
      slots: [],
      annotations: {
        framerVariables: '{"kL7AaSDtq":"click"}',
        framerIntrinsicWidth: "178",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ucnq_bol5":{"layout":["fixed","fixed"]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "220",
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./wy75ZqvAY.map
