// Generated by Framer (98b71dc)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Image3 from "https://framerusercontent.com/modules/1WrNYbYhZnmc0ejoY2fI/XP8r5fVt6DGZIsDg4sxh/B1Ub1cYXx.js";
const Image3Fonts = getFonts(Image3);
const MotionDivWithFX = withFX(motion.div);
const SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
  withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
const enabledGestures = {
  VkvE7meVY: { hover: true },
  xsSF32EV4: { hover: true },
};
const cycleOrder = ["xsSF32EV4", "VkvE7meVY", "hKzYhjHMi", "Irp5_KpWG"];
const serializationHash = "framer-ZWTE6";
const variantClassNames = {
  hKzYhjHMi: "framer-v-1nzg253",
  Irp5_KpWG: "framer-v-13w7lav",
  VkvE7meVY: "framer-v-1wvcl87",
  xsSF32EV4: "framer-v-18dyj40",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const animation3 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.5,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
  const [visible, setVisible] = useOverlayState({ blockDocumentScrolling });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "no hover": "Irp5_KpWG",
  "Variant 1": "xsSF32EV4",
  "Variant 2": "VkvE7meVY",
  "Variant 3": "hKzYhjHMi",
};
const getProps = ({ fontSize, height, id, width, ...props }) => {
  return {
    ...props,
    nIzqBU6De: fontSize ?? props.nIzqBU6De ?? 42,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "xsSF32EV4",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, nIzqBU6De, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "xsSF32EV4",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnterupml6a = ({ overlay, loadMore }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isHovered: true });
      overlay.show();
    });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "VkvE7meVY-hover") return true;
    return false;
  };
  const ref1 = React.useRef(null);
  const isDisplayed1 = () => {
    if (baseVariant === "hKzYhjHMi") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Overlay, {
        blockDocumentScrolling: false,
        enabled: isDisplayed(),
        children: (overlay) =>
          /*#__PURE__*/ _jsx(_Fragment, {
            children: /*#__PURE__*/ _jsx(Transition, {
              value: transition1,
              children: /*#__PURE__*/ _jsxs(motion.div, {
                ...restProps,
                ...gestureHandlers,
                className: cx(
                  scopingClassNames,
                  "framer-18dyj40",
                  className,
                  classNames
                ),
                "data-framer-name": "Variant 1",
                "data-highlight": true,
                id: `${layoutId}-18dyj40`,
                layoutDependency: layoutDependency,
                layoutId: "xsSF32EV4",
                onMouseEnter: onMouseEnterupml6a({ overlay }),
                ref: refBinding,
                style: { ...style },
                ...addPropertyOverrides(
                  {
                    "VkvE7meVY-hover": { "data-framer-name": undefined },
                    "xsSF32EV4-hover": { "data-framer-name": undefined },
                    hKzYhjHMi: { "data-framer-name": "Variant 3" },
                    Irp5_KpWG: { "data-framer-name": "no hover" },
                    VkvE7meVY: { "data-framer-name": "Variant 2" },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-13p5ude",
                    layoutDependency: layoutDependency,
                    layoutId: "W6A5LfeTK",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "003.",
                          }),
                        }),
                        className: "framer-1dryq4y",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "vsf_Lpqv4",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-nIzqBU6De-TxwW3cLrj": nIzqBU6De,
                        },
                        variants: {
                          "VkvE7meVY-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                          "xsSF32EV4-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                          hKzYhjHMi: {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "VkvE7meVY-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "003",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            "xsSF32EV4-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "003",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            hKzYhjHMi: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "003",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                              "--framer-font-family":
                                '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                              "--framer-font-size":
                                "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                              "--framer-letter-spacing": "-1px",
                              "--framer-line-height": "120%",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, rgb(61, 61, 61))",
                              "--framer-text-transform": "uppercase",
                            },
                            children: "TAKE NO PRISONERS.",
                          }),
                        }),
                        className: "framer-fccktz",
                        fonts: ["CUSTOM;GT Flexa Mono Trial Md"],
                        layoutDependency: layoutDependency,
                        layoutId: "z_RvvG8YV",
                        style: {
                          "--extracted-1lwpl3i": "rgb(61, 61, 61)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          "--variable-reference-nIzqBU6De-TxwW3cLrj": nIzqBU6De,
                        },
                        variants: {
                          "VkvE7meVY-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                          },
                          "xsSF32EV4-hover": {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36))",
                          },
                          hKzYhjHMi: {
                            "--extracted-1lwpl3i":
                              "var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238))",
                            "--extracted-as4nhg":
                              "var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            "VkvE7meVY-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: "TAKE NO PRISONERS.",
                                }),
                              }),
                            },
                            "xsSF32EV4-hover": {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "TAKE NO PRISONERS",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(255, 76, 36)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                            hKzYhjHMi: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h5, {
                                  style: {
                                    "--font-selector":
                                      "Q1VTVE9NO0dUIEZsZXhhIE1vbm8gVHJpYWwgTWQ=",
                                    "--framer-font-family":
                                      '"GT Flexa Mono Trial Md", "GT Flexa Mono Trial Md Placeholder", monospace',
                                    "--framer-font-size":
                                      "calc(var(--variable-reference-nIzqBU6De-TxwW3cLrj) * 1px)",
                                    "--framer-letter-spacing": "-1px",
                                    "--framer-line-height": "120%",
                                    "--framer-text-color":
                                      "var(--extracted-1lwpl3i, var(--token-695b32f7-75d5-4e5d-bf3a-4e49b9e227e2, rgb(244, 241, 238)))",
                                    "--framer-text-transform": "uppercase",
                                  },
                                  children: [
                                    "TAKE NO PRISONERS",
                                    /*#__PURE__*/ _jsx(motion.span, {
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-as4nhg, var(--token-1c6e322e-f01f-4ab1-84f3-13b6c06eac87, rgb(244, 72, 73)))",
                                      },
                                      children: ".",
                                    }),
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    ],
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(AnimatePresence, {
                      children:
                        overlay.visible &&
                        /*#__PURE__*/ _jsx(Floating, {
                          alignment: "center",
                          anchorRef: refBinding,
                          className: cx(scopingClassNames, classNames),
                          collisionDetection: true,
                          collisionDetectionPadding: 20,
                          "data-framer-portal-id": `${layoutId}-18dyj40`,
                          offsetX: 0,
                          offsetY: 10,
                          onDismiss: overlay.hide,
                          placement: "bottom",
                          safeArea: true,
                          zIndex: 11,
                          children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation1,
                            className: "framer-17ovxjk",
                            exit: animation,
                            initial: animation2,
                            layoutDependency: layoutDependency,
                            layoutId: "BeKdO74kY",
                            ref: ref1,
                            role: "dialog",
                            style: {
                              backgroundColor: "rgb(255, 255, 255)",
                              borderBottomLeftRadius: 10,
                              borderBottomRightRadius: 10,
                              borderTopLeftRadius: 10,
                              borderTopRightRadius: 10,
                              boxShadow:
                                "0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
                            },
                            variants: {
                              "VkvE7meVY-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                boxShadow: "none",
                              },
                            },
                            children: /*#__PURE__*/ _jsx(
                              ComponentViewportProvider,
                              {
                                width: "240px",
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-1ml9ou-container",
                                    "data-framer-name": "003",
                                    layoutDependency: layoutDependency,
                                    layoutId: "DSqblbNeP-container",
                                    name: "003",
                                    nodeId: "DSqblbNeP",
                                    rendersWithMotion: true,
                                    scopeId: "TxwW3cLrj",
                                    children: /*#__PURE__*/ _jsx(Image3, {
                                      height: "100%",
                                      id: "DSqblbNeP",
                                      layoutId: "DSqblbNeP",
                                      name: "003",
                                      style: { height: "100%", width: "100%" },
                                      variant: "rzcmrDp5O",
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }
                            ),
                          }),
                        }),
                    }),
                  isDisplayed1() &&
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      ...addPropertyOverrides(
                        {
                          hKzYhjHMi: {
                            height: 153,
                            width: "240px",
                            y:
                              (componentViewport?.y || 0) +
                              (componentViewport?.height || 50.5) -
                              -10,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                        {
                          __perspectiveFX: false,
                          __smartComponentFX: true,
                          __targetOpacity: 1,
                          animate: animation1,
                          className: "framer-1yyupr7-container",
                          "data-framer-appear-id": "1yyupr7",
                          "data-framer-name": "003",
                          initial: animation3,
                          layoutDependency: layoutDependency,
                          layoutId: "Mm2QLGHUc-container",
                          name: "003",
                          nodeId: "Mm2QLGHUc",
                          optimized: true,
                          rendersWithMotion: true,
                          scopeId: "TxwW3cLrj",
                          children: /*#__PURE__*/ _jsx(Image3, {
                            height: "100%",
                            id: "Mm2QLGHUc",
                            layoutId: "Mm2QLGHUc",
                            name: "003",
                            style: { height: "100%", width: "100%" },
                            variant: "rzcmrDp5O",
                            width: "100%",
                          }),
                        }
                      ),
                    }),
                ],
              }),
            }),
          }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ZWTE6.framer-qzabmf, .framer-ZWTE6 .framer-qzabmf { display: block; }",
  ".framer-ZWTE6.framer-18dyj40 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
  ".framer-ZWTE6 .framer-13p5ude { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-ZWTE6 .framer-1dryq4y { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-ZWTE6 .framer-fccktz { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-ZWTE6 .framer-17ovxjk { height: 150px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-ZWTE6 .framer-1ml9ou-container { flex: none; height: 168px; left: calc(50.00000000000002% - 240px / 2); position: absolute; top: 9px; width: 240px; }",
  ".framer-ZWTE6 .framer-1yyupr7-container { bottom: -163px; flex: none; height: 153px; left: calc(50.00000000000002% - 240px / 2); position: absolute; width: 240px; z-index: 1; }",
  ".framer-ZWTE6.framer-v-1nzg253.framer-18dyj40 { cursor: unset; overflow: visible; }",
  ".framer-ZWTE6.framer-v-13w7lav.framer-18dyj40 { cursor: unset; }",
  ".framer-ZWTE6.framer-v-1wvcl87.hover .framer-17ovxjk { height: 160px; width: 260px; }",
  ".framer-ZWTE6.framer-v-1wvcl87.hover .framer-1ml9ou-container { bottom: 0px; height: 153px; top: unset; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 50.5
 * @framerIntrinsicWidth 1100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VkvE7meVY":{"layout":["fixed","auto"]},"hKzYhjHMi":{"layout":["fixed","auto"]},"Irp5_KpWG":{"layout":["fixed","auto"]},"Yf4YURDcQ":{"layout":["fixed","auto"]},"zwwwZ_LPz":{"layout":["fixed","auto"]}}}
 * @framerVariables {"nIzqBU6De":"fontSize"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerTxwW3cLrj = withCSS(Component, css, "framer-ZWTE6");
export default FramerTxwW3cLrj;
FramerTxwW3cLrj.displayName = "003";
FramerTxwW3cLrj.defaultProps = { height: 50.5, width: 1100 };
addPropertyControls(FramerTxwW3cLrj, {
  variant: {
    options: ["xsSF32EV4", "VkvE7meVY", "hKzYhjHMi", "Irp5_KpWG"],
    optionTitles: ["Variant 1", "Variant 2", "Variant 3", "no hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
  nIzqBU6De: { defaultValue: 42, title: "Font Size", type: ControlType.Number },
});
addFonts(
  FramerTxwW3cLrj,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "GT Flexa Mono Trial Md",
          source: "custom",
          uiFamilyName: "GT Flexa Mono Trial Md",
          url: "https://framerusercontent.com/assets/bytIjhUjhiCYHWtmBe4nrOXxwJM.woff2",
        },
      ],
    },
    ...Image3Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerTxwW3cLrj",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VkvE7meVY":{"layout":["fixed","auto"]},"hKzYhjHMi":{"layout":["fixed","auto"]},"Irp5_KpWG":{"layout":["fixed","auto"]},"Yf4YURDcQ":{"layout":["fixed","auto"]},"zwwwZ_LPz":{"layout":["fixed","auto"]}}}',
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "1100",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerVariables: '{"nIzqBU6De":"fontSize"}',
        framerIntrinsicHeight: "50.5",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./TxwW3cLrj.map
