// Generated by Framer (2ac8f15)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Phase1 from "https://framerusercontent.com/modules/weygpgv6OmhZfqIWMGpt/7IhE6T2f5s6gGT8utxNc/MFzFsGZ3T.js";
import Phase3 from "https://framerusercontent.com/modules/3qFwV2t3gdutkHtt8bOB/k5C3FbWlWgDeAnGxUDII/PEWGz3ks0.js";
import Phase2 from "https://framerusercontent.com/modules/9cNdv9QmOB4HbbQjwWF5/YpuDGoDVkkvAf8Py0sHo/uSQKcGJsm.js";
import Phase4 from "https://framerusercontent.com/modules/9V7sI5V3Zj4KZnYKxX4B/D4TEGUtHsIkuKP041U4n/UWio70edc.js";
const Phase1Fonts = getFonts(Phase1);
const Phase2Fonts = getFonts(Phase2);
const Phase3Fonts = getFonts(Phase3);
const Phase4Fonts = getFonts(Phase4);
const cycleOrder = ["y__q1nPZj", "P5CagX797", "BQJw3dP9_", "YdeR8Bh5K"];
const serializationHash = "framer-HeQTp";
const variantClassNames = {
  BQJw3dP9_: "framer-v-4i0fio",
  P5CagX797: "framer-v-2r45dy",
  y__q1nPZj: "framer-v-dgqmjx",
  YdeR8Bh5K: "framer-v-dhv5ym",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "y__q1nPZj",
  "Variant 2": "P5CagX797",
  "Variant 3": "BQJw3dP9_",
  "Variant 4": "YdeR8Bh5K",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "y__q1nPZj",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "y__q1nPZj",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const J_EfI3gzX188t0ys = activeVariantCallback(async (...args) => {
    setVariant("y__q1nPZj");
  });
  const i6vlZsiGO1a643lx = activeVariantCallback(async (...args) => {
    setVariant("P5CagX797");
  });
  const gpj0NrccQ11jz9ob = activeVariantCallback(async (...args) => {
    setVariant("BQJw3dP9_");
  });
  const cw3H0tdvi1i0896l = activeVariantCallback(async (...args) => {
    setVariant("YdeR8Bh5K");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-dgqmjx",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "y__q1nPZj",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgb(44, 44, 44)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor: "rgb(0, 0, 0)",
            borderBottomLeftRadius: 10,
            borderBottomRightRadius: 10,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            ...style,
          },
          ...addPropertyOverrides(
            {
              BQJw3dP9_: { "data-framer-name": "Variant 3" },
              P5CagX797: { "data-framer-name": "Variant 2" },
              YdeR8Bh5K: { "data-framer-name": "Variant 4" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1rcsbmz",
            layoutDependency: layoutDependency,
            layoutId: "kROEyQm_K",
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1jid0uh",
                "data-border": true,
                "data-framer-name": "Left Sidebar",
                layoutDependency: layoutDependency,
                layoutId: "frP8CPh6T",
                style: {
                  "--border-bottom-width": "1px",
                  "--border-color": "rgba(239, 238, 236, 0.08)",
                  "--border-left-width": "1px",
                  "--border-right-width": "1px",
                  "--border-style": "solid",
                  "--border-top-width": "1px",
                  backgroundColor: "rgb(14, 14, 14)",
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8,
                },
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-bou850",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "nsKzQO5nO",
                  children: /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-xd7uaz",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "RRW97Jxlr",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1axhs7p",
                        "data-framer-name": "home",
                        layoutDependency: layoutDependency,
                        layoutId: "gTmZUUYxU",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                  "--framer-font-size": "24px",
                                  "--framer-letter-spacing": "-1px",
                                  "--framer-line-height": "48px",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                },
                                children: "Honey",
                              }),
                            }),
                            className: "framer-1mbzzs",
                            "data-framer-name": "Task Name",
                            fonts: ["GF;Suisse Int'l-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "p2eZVfAF9",
                            style: {
                              "--extracted-r6o4lv": "rgb(255, 255, 255)",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "center",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-1g5nsbg",
                            "data-framer-name": "noun-honey-6452526 1",
                            fill: "rgba(0,0,0,1)",
                            intrinsicHeight: 18,
                            intrinsicWidth: 18,
                            layoutDependency: layoutDependency,
                            layoutId: "v3YooszPH",
                            svg: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_24_279)">\n<path d="M9.82801 4.66243L8.83801 8.35243L11.538 11.0524L15.21 10.0624L16.2 6.37243L13.5 3.69043L9.82801 4.66243Z" fill="white"/>\n<path d="M8.18997 8.17181L9.16199 4.49981L6.47999 1.7998L2.78999 2.7898L1.79999 6.46181L4.49999 9.16181L8.18997 8.17181Z" fill="white"/>\n<path d="M3.69 13.4999L6.39 16.1999L10.062 15.2099L11.052 11.5379L8.352 8.83789L4.68 9.82789L3.69 13.4999Z" fill="white"/>\n<path d="M10.7324 15.4472L13.4856 18.0929L17.1372 17.0299L18.0538 13.3389L15.3005 10.6932L11.649 11.7562L10.7324 15.4472Z" fill="white"/>\n</g>\n<defs>\n<clipPath id="clip0_24_279">\n<rect width="18" height="18" fill="white"/>\n</clipPath>\n</defs>\n</svg>\n',
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-wwz9ka",
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "bKMtArCYq",
                        transformTemplate: transformTemplate1,
                        children: [
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 51,
                            width: `calc(max(${
                              componentViewport?.width || "100vw"
                            } - 16px, 1px) * 0.1738)`,
                            y:
                              (componentViewport?.y || 0) +
                              (8 +
                                ((componentViewport?.height || 881) -
                                  16 -
                                  865) /
                                  2) +
                              0 +
                              0 +
                              0 +
                              105 +
                              0 +
                              0,
                            ...addPropertyOverrides(
                              {
                                BQJw3dP9_: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    0,
                                },
                                YdeR8Bh5K: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    0,
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-1oeekg3-container",
                                layoutDependency: layoutDependency,
                                layoutId: "m5QAllExi-container",
                                nodeId: "m5QAllExi",
                                rendersWithMotion: true,
                                scopeId: "OTPOYii8D",
                                children: /*#__PURE__*/ _jsx(Phase1, {
                                  height: "100%",
                                  id: "m5QAllExi",
                                  J_EfI3gzX: J_EfI3gzX188t0ys,
                                  layoutId: "m5QAllExi",
                                  style: { width: "100%" },
                                  variant: "qo1xAtgXG",
                                  width: "100%",
                                  ...addPropertyOverrides(
                                    {
                                      BQJw3dP9_: { variant: "Ix4txGx55" },
                                      P5CagX797: { variant: "Ix4txGx55" },
                                      YdeR8Bh5K: { variant: "Ix4txGx55" },
                                    },
                                    baseVariant,
                                    gestureVariant
                                  ),
                                }),
                              }
                            ),
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 51,
                            width: `calc(max(${
                              componentViewport?.width || "100vw"
                            } - 16px, 1px) * 0.1738)`,
                            y:
                              (componentViewport?.y || 0) +
                              (8 +
                                ((componentViewport?.height || 881) -
                                  16 -
                                  865) /
                                  2) +
                              0 +
                              0 +
                              0 +
                              105 +
                              0 +
                              67,
                            ...addPropertyOverrides(
                              {
                                BQJw3dP9_: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    67,
                                },
                                YdeR8Bh5K: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    67,
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-14mujda-container",
                                layoutDependency: layoutDependency,
                                layoutId: "tkQinlMjC-container",
                                nodeId: "tkQinlMjC",
                                rendersWithMotion: true,
                                scopeId: "OTPOYii8D",
                                children: /*#__PURE__*/ _jsx(Phase2, {
                                  height: "100%",
                                  i6vlZsiGO: i6vlZsiGO1a643lx,
                                  id: "tkQinlMjC",
                                  layoutId: "tkQinlMjC",
                                  style: { width: "100%" },
                                  variant: "I2Yi3iDda",
                                  width: "100%",
                                  ...addPropertyOverrides(
                                    { P5CagX797: { variant: "WiDeAGnCp" } },
                                    baseVariant,
                                    gestureVariant
                                  ),
                                }),
                              }
                            ),
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 51,
                            width: `calc(max(${
                              componentViewport?.width || "100vw"
                            } - 16px, 1px) * 0.1738)`,
                            y:
                              (componentViewport?.y || 0) +
                              (8 +
                                ((componentViewport?.height || 881) -
                                  16 -
                                  865) /
                                  2) +
                              0 +
                              0 +
                              0 +
                              105 +
                              0 +
                              134,
                            ...addPropertyOverrides(
                              {
                                BQJw3dP9_: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    134,
                                },
                                YdeR8Bh5K: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    134,
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-aoz0dt-container",
                                layoutDependency: layoutDependency,
                                layoutId: "a5Aq09FNG-container",
                                nodeId: "a5Aq09FNG",
                                rendersWithMotion: true,
                                scopeId: "OTPOYii8D",
                                children: /*#__PURE__*/ _jsx(Phase3, {
                                  gpj0NrccQ: gpj0NrccQ11jz9ob,
                                  height: "100%",
                                  id: "a5Aq09FNG",
                                  layoutId: "a5Aq09FNG",
                                  style: { width: "100%" },
                                  variant: "CxgBertp4",
                                  width: "100%",
                                  ...addPropertyOverrides(
                                    { BQJw3dP9_: { variant: "V5coAxEE4" } },
                                    baseVariant,
                                    gestureVariant
                                  ),
                                }),
                              }
                            ),
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 51,
                            width: `calc(max(${
                              componentViewport?.width || "100vw"
                            } - 16px, 1px) * 0.1738)`,
                            y:
                              (componentViewport?.y || 0) +
                              (8 +
                                ((componentViewport?.height || 881) -
                                  16 -
                                  865) /
                                  2) +
                              0 +
                              0 +
                              0 +
                              105 +
                              0 +
                              201,
                            ...addPropertyOverrides(
                              {
                                BQJw3dP9_: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    201,
                                },
                                YdeR8Bh5K: {
                                  y:
                                    (componentViewport?.y || 0) +
                                    (8 +
                                      ((componentViewport?.height || 200) -
                                        16 -
                                        865) /
                                        2) +
                                    0 +
                                    0 +
                                    0 +
                                    105 +
                                    0 +
                                    201,
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-1ngopa4-container",
                                layoutDependency: layoutDependency,
                                layoutId: "rlwVlLuM5-container",
                                nodeId: "rlwVlLuM5",
                                rendersWithMotion: true,
                                scopeId: "OTPOYii8D",
                                children: /*#__PURE__*/ _jsx(Phase4, {
                                  cw3H0tdvi: cw3H0tdvi1i0896l,
                                  height: "100%",
                                  id: "rlwVlLuM5",
                                  layoutId: "rlwVlLuM5",
                                  style: { width: "100%" },
                                  variant: "NdDsfaeKz",
                                  width: "100%",
                                  ...addPropertyOverrides(
                                    { YdeR8Bh5K: { variant: "VrMhlCJP0" } },
                                    baseVariant,
                                    gestureVariant
                                  ),
                                }),
                              }
                            ),
                          }),
                        ],
                      }),
                    ],
                  }),
                }),
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1nwq1m0",
                "data-border": true,
                "data-framer-name": "Background",
                layoutDependency: layoutDependency,
                layoutId: "vWX5rZJSQ",
                style: {
                  "--border-bottom-width": "1px",
                  "--border-color": "rgb(44, 44, 44)",
                  "--border-left-width": "1px",
                  "--border-right-width": "1px",
                  "--border-style": "solid",
                  "--border-top-width": "1px",
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8,
                },
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-7f7ctd",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "WewuSJye8",
                    children: [
                      /*#__PURE__*/ _jsx(SVG, {
                        className: "framer-dfumyt",
                        "data-framer-name": "Union",
                        fill: "rgba(0,0,0,1)",
                        intrinsicHeight: 17,
                        intrinsicWidth: 17,
                        layoutDependency: layoutDependency,
                        layoutId: "OafOwZj6_",
                        svg: '<svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M16.1342 14.8737H0.134155V16.1689H16.1342V14.8737ZM0.134155 0.167604L0.134156 14.8705H1.42944L1.42944 0.167604H0.134155Z" fill="#FF5732"/>\n</svg>\n',
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(SVG, {
                        className: "framer-1mwew28",
                        "data-framer-name": "Union",
                        fill: "rgba(0,0,0,1)",
                        intrinsicHeight: 17,
                        intrinsicWidth: 17,
                        layoutDependency: layoutDependency,
                        layoutId: "D_ZxWgGrh",
                        svg: '<svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M0.817505 14.8746H16.8175V16.1699H0.817505V14.8746ZM16.8174 0.168581L16.8174 14.8715H15.5221L15.5221 0.168581H16.8174Z" fill="#FF5732"/>\n</svg>\n',
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(SVG, {
                        className: "framer-13b0rgt",
                        "data-framer-name": "Union",
                        fill: "rgba(0,0,0,1)",
                        intrinsicHeight: 17,
                        intrinsicWidth: 17,
                        layoutDependency: layoutDependency,
                        layoutId: "eSsH4HJOx",
                        svg: '<svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M0.817505 2.12732H16.8175V0.832031H0.817505V2.12732ZM16.8174 16.8334L16.8174 2.13048H15.5221L15.5221 16.8334H16.8174Z" fill="#FF5732"/>\n</svg>\n',
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(SVG, {
                        className: "framer-15eo2ua",
                        "data-framer-name": "Union",
                        fill: "rgba(0,0,0,1)",
                        intrinsicHeight: 17,
                        intrinsicWidth: 17,
                        layoutDependency: layoutDependency,
                        layoutId: "sgyY_cjze",
                        svg: '<svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M16.134 2.12732H0.133972V0.832031H16.134V2.12732ZM0.133972 16.8334L0.133973 2.13048H1.42926L1.42926 16.8334H0.133972Z" fill="#FF5732"/>\n</svg>\n',
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-sxnbns",
                        "data-border": true,
                        "data-framer-name": "Container",
                        layoutDependency: layoutDependency,
                        layoutId: "m2zEeHxta",
                        style: {
                          "--border-bottom-width": "0.647643506526947px",
                          "--border-color": "rgb(34, 34, 34)",
                          "--border-left-width": "0.647643506526947px",
                          "--border-right-width": "0.647643506526947px",
                          "--border-style": "solid",
                          "--border-top-width": "0.647643506526947px",
                          backgroundColor: "rgb(20, 20, 20)",
                          borderBottomLeftRadius: 10.36,
                          borderBottomRightRadius: 10.36,
                          borderTopLeftRadius: 10.36,
                          borderTopRightRadius: 10.36,
                        },
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                  "--framer-font-size": "32px",
                                  "--framer-letter-spacing": "-1px",
                                  "--framer-line-height": "120%",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(233, 233, 233))",
                                },
                                children: "01. Rendezvous",
                              }),
                            }),
                            className: "framer-1cxwo7r",
                            "data-framer-name": "Heading 2 → Use cases",
                            fonts: ["GF;Suisse Int'l-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "pRUU3e2P3",
                            style: {
                              "--extracted-r6o4lv": "rgb(233, 233, 233)",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "center",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                BQJw3dP9_: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      style: {
                                        "--font-selector":
                                          "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                        "--framer-font-family":
                                          '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                        "--framer-font-size": "32px",
                                        "--framer-letter-spacing": "-1px",
                                        "--framer-line-height": "120%",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(233, 233, 233))",
                                      },
                                      children: "03. The Exhibition",
                                    }),
                                  }),
                                },
                                P5CagX797: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      style: {
                                        "--font-selector":
                                          "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                        "--framer-font-family":
                                          '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                        "--framer-font-size": "32px",
                                        "--framer-letter-spacing": "-1px",
                                        "--framer-line-height": "120%",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(233, 233, 233))",
                                      },
                                      children: "02. The Silence",
                                    }),
                                  }),
                                },
                                YdeR8Bh5K: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      style: {
                                        "--font-selector":
                                          "R0Y7U3Vpc3NlIEludCdsLXJlZ3VsYXI=",
                                        "--framer-font-family":
                                          '"Suisse Int\'l", "Suisse Int\'l Placeholder", sans-serif',
                                        "--framer-font-size": "32px",
                                        "--framer-letter-spacing": "-1px",
                                        "--framer-line-height": "120%",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(233, 233, 233))",
                                      },
                                      children: "04. The Alterations",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                  "--framer-font-family":
                                    '"GT Flexa Mono Trial", monospace',
                                  "--framer-font-size": "12px",
                                  "--framer-line-height": "150%",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(134, 134, 134))",
                                  "--framer-text-transform": "uppercase",
                                },
                                children:
                                  "We meet every other Friday to review the work of the previous sprint and outline the next one. Think of it like that war room in World of WarCraft right before Leroy Jenkins charges into the void.",
                              }),
                            }),
                            className: "framer-1dyrjb1",
                            "data-framer-name": "Description",
                            fonts: ["GF;GT Flexa Mono Trial-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "xBNIkd3dx",
                            style: {
                              "--extracted-r6o4lv": "rgb(134, 134, 134)",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "center",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                BQJw3dP9_: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      style: {
                                        "--font-selector":
                                          "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                        "--framer-font-family":
                                          '"GT Flexa Mono Trial", monospace',
                                        "--framer-font-size": "12px",
                                        "--framer-line-height": "150%",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(134, 134, 134))",
                                        "--framer-text-transform": "uppercase",
                                      },
                                      children:
                                        "We present the work from each sprint every other Friday with as much flair as The Bulls circa 1996. If you want us to show up and present the work to you in person, that’s fine too. But, we fly first-class and we’re not covering our own airfare. So, Zoom is a hell of a lot cheaper.",
                                    }),
                                  }),
                                },
                                P5CagX797: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      style: {
                                        "--font-selector":
                                          "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                        "--framer-font-family":
                                          '"GT Flexa Mono Trial", monospace',
                                        "--framer-font-size": "12px",
                                        "--framer-line-height": "150%",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(134, 134, 134))",
                                        "--framer-text-transform": "uppercase",
                                      },
                                      children:
                                        "Like blacksmiths, we do our best work heads down and nose to the grindstone. With that said, every enterprise worth its weight in gold has made more pivots than a joystick in an arcade bar. So, like a good neighbor when you come a-knockin' for sugar or an egg, we try and always answer the door.",
                                    }),
                                  }),
                                },
                                YdeR8Bh5K: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      style: {
                                        "--font-selector":
                                          "R0Y7R1QgRmxleGEgTW9ubyBUcmlhbC1yZWd1bGFy",
                                        "--framer-font-family":
                                          '"GT Flexa Mono Trial", monospace',
                                        "--framer-font-size": "12px",
                                        "--framer-line-height": "150%",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(134, 134, 134))",
                                        "--framer-text-transform": "uppercase",
                                      },
                                      children:
                                        "You “circle the wagons” internally and put together a list of edits you’d like to see made. Barring holidays, acts of God and global catastrophes, we usually get your revised alterations back to you within 48 hours.",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-12bdkj7",
                    "data-framer-name": "sprints",
                    layoutDependency: layoutDependency,
                    layoutId: "k3Av3xK0S",
                    style: {
                      backgroundColor: "rgb(10, 10, 10)",
                      borderBottomLeftRadius: 18.58,
                      borderBottomRightRadius: 18.58,
                      borderTopLeftRadius: 18.58,
                      borderTopRightRadius: 18.58,
                      boxShadow:
                        "0px 0px 0px 1.547998070716858px rgba(255, 255, 255, 0.14), 0px 1.547998070716858px 3.095996141433716px 0px rgba(0, 0, 0, 0.16), 0px 4.272279262542725px 85.44558715820312px 21.36139678955078px rgba(255, 76, 36, 0.1)",
                    },
                    children: /*#__PURE__*/ _jsx(Image, {
                      background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            (8 +
                              ((componentViewport?.height || 881) - 16 - 865) /
                                2) +
                            0 +
                            865 -
                            543 +
                            -5
                        ),
                        pixelHeight: 1813,
                        pixelWidth: 1920,
                        positionX: "center",
                        positionY: "center",
                        sizes: "845px",
                        src: "https://framerusercontent.com/images/u7vQBJKJoCxpNVGjab1tQX5Xj4.jpg",
                        srcSet:
                          "https://framerusercontent.com/images/u7vQBJKJoCxpNVGjab1tQX5Xj4.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/u7vQBJKJoCxpNVGjab1tQX5Xj4.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/u7vQBJKJoCxpNVGjab1tQX5Xj4.jpg 1920w",
                      },
                      className: "framer-1m8toua",
                      layoutDependency: layoutDependency,
                      layoutId: "JOQPjylqX",
                      ...addPropertyOverrides(
                        {
                          BQJw3dP9_: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  (8 +
                                    ((componentViewport?.height || 200) -
                                      16 -
                                      865) /
                                      2) +
                                  0 +
                                  865 -
                                  543 +
                                  -5
                              ),
                              pixelHeight: 1075,
                              pixelWidth: 1600,
                              positionX: "center",
                              positionY: "center",
                              sizes: "845px",
                              src: "https://framerusercontent.com/images/oY3yKVpvBqsP8H43FvjiGeneW6E.jpg",
                              srcSet:
                                "https://framerusercontent.com/images/oY3yKVpvBqsP8H43FvjiGeneW6E.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/oY3yKVpvBqsP8H43FvjiGeneW6E.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/oY3yKVpvBqsP8H43FvjiGeneW6E.jpg 1600w",
                            },
                          },
                          P5CagX797: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  (8 +
                                    ((componentViewport?.height || 881) -
                                      16 -
                                      865) /
                                      2) +
                                  0 +
                                  865 -
                                  543 +
                                  -5
                              ),
                              pixelHeight: 1826,
                              pixelWidth: 2560,
                              positionX: "center",
                              positionY: "center",
                              sizes: "845px",
                              src: "https://framerusercontent.com/images/5Sev9JEFponv8RlJ9AI5qpNntQk.jpg",
                              srcSet:
                                "https://framerusercontent.com/images/5Sev9JEFponv8RlJ9AI5qpNntQk.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/5Sev9JEFponv8RlJ9AI5qpNntQk.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/5Sev9JEFponv8RlJ9AI5qpNntQk.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/5Sev9JEFponv8RlJ9AI5qpNntQk.jpg 2560w",
                            },
                          },
                          YdeR8Bh5K: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  (8 +
                                    ((componentViewport?.height || 200) -
                                      16 -
                                      865) /
                                      2) +
                                  0 +
                                  865 -
                                  543 +
                                  -5
                              ),
                              pixelHeight: 3239,
                              pixelWidth: 4501,
                              positionX: "center",
                              positionY: "center",
                              sizes: "845px",
                              src: "https://framerusercontent.com/images/kM2zDHeI4OWePLEa0u5rkG9F42Y.jpg",
                              srcSet:
                                "https://framerusercontent.com/images/kM2zDHeI4OWePLEa0u5rkG9F42Y.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/kM2zDHeI4OWePLEa0u5rkG9F42Y.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/kM2zDHeI4OWePLEa0u5rkG9F42Y.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/kM2zDHeI4OWePLEa0u5rkG9F42Y.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/kM2zDHeI4OWePLEa0u5rkG9F42Y.jpg 4501w",
                            },
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1kixbsz",
                        "data-framer-name": "Gradient",
                        layoutDependency: layoutDependency,
                        layoutId: "VD5YZlxxn",
                        style: {
                          background:
                            "linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgb(0, 0, 0) 107%)",
                          borderBottomLeftRadius: 18.58,
                          borderBottomRightRadius: 18.58,
                          borderTopLeftRadius: 18.58,
                          borderTopRightRadius: 18.58,
                        },
                      }),
                    }),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-HeQTp.framer-1q0ljwk, .framer-HeQTp .framer-1q0ljwk { display: block; }",
  ".framer-HeQTp.framer-dgqmjx { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 8px; position: relative; width: 1512px; }",
  ".framer-HeQTp .framer-1rcsbmz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-HeQTp .framer-1jid0uh { flex: none; gap: 0px; height: 865px; overflow: visible; position: relative; width: 19%; }",
  ".framer-HeQTp .framer-bou850 { flex: none; gap: 0px; height: 863px; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
  ".framer-HeQTp .framer-xd7uaz { flex: none; gap: 0px; height: 705px; left: 0px; overflow: visible; position: absolute; top: 0px; width: 100%; }",
  ".framer-HeQTp .framer-1axhs7p { flex: none; gap: 0px; height: 67px; left: 16px; overflow: visible; position: absolute; right: 14px; top: 0px; }",
  ".framer-HeQTp .framer-1mbzzs { flex: none; height: auto; left: 13px; position: absolute; top: 37px; white-space: pre; width: auto; }",
  ".framer-HeQTp .framer-1g5nsbg { bottom: 0px; flex: none; height: 18px; position: absolute; right: 10px; width: 18px; }",
  ".framer-HeQTp .framer-wwz9ka { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 105px; width: 90%; }",
  ".framer-HeQTp .framer-1oeekg3-container, .framer-HeQTp .framer-14mujda-container, .framer-HeQTp .framer-aoz0dt-container, .framer-HeQTp .framer-1ngopa4-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-HeQTp .framer-1nwq1m0 { flex: 1 0 0px; height: 865px; position: relative; width: 1px; }",
  ".framer-HeQTp .framer-7f7ctd { flex: none; height: 193px; left: 80px; overflow: visible; position: absolute; right: 74px; top: 85px; }",
  ".framer-HeQTp .framer-dfumyt { bottom: -3px; flex: none; height: 17px; left: 0px; position: absolute; width: 17px; }",
  ".framer-HeQTp .framer-1mwew28 { bottom: -3px; flex: none; height: 17px; position: absolute; right: 0px; width: 17px; }",
  ".framer-HeQTp .framer-13b0rgt { flex: none; height: 17px; position: absolute; right: 0px; top: -1px; width: 17px; }",
  ".framer-HeQTp .framer-15eo2ua { flex: none; height: 17px; left: 0px; position: absolute; top: 0px; width: 17px; }",
  ".framer-HeQTp .framer-sxnbns { align-content: center; align-items: center; bottom: 21px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 17px; overflow: visible; padding: 32px; position: absolute; right: 17px; }",
  ".framer-HeQTp .framer-1cxwo7r, .framer-HeQTp .framer-1dyrjb1 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-HeQTp .framer-12bdkj7 { bottom: 63px; flex: none; gap: 0px; height: 480px; left: calc(50.08361204013381% - 762px / 2); overflow: hidden; position: absolute; width: 762px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-HeQTp .framer-1m8toua { bottom: 0px; flex: none; left: -41px; position: absolute; right: -42px; top: -5px; }",
  ".framer-HeQTp .framer-1kixbsz { bottom: 0px; flex: none; left: calc(49.94082840236689% - 763px / 2); position: absolute; top: 0px; width: 763px; }",
  ".framer-HeQTp.framer-v-2r45dy .framer-sxnbns, .framer-HeQTp.framer-v-4i0fio .framer-sxnbns { bottom: 11px; }",
  ".framer-HeQTp.framer-v-dhv5ym .framer-1kixbsz { left: calc(49.82248520710061% - 763px / 2); }",
  '.framer-HeQTp[data-border="true"]::after, .framer-HeQTp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 881
 * @framerIntrinsicWidth 1512
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"P5CagX797":{"layout":["fixed","auto"]},"BQJw3dP9_":{"layout":["fixed","auto"]},"YdeR8Bh5K":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerOTPOYii8D = withCSS(Component, css, "framer-HeQTp");
export default FramerOTPOYii8D;
FramerOTPOYii8D.displayName = "Mockup-Wider";
FramerOTPOYii8D.defaultProps = { height: 881, width: 1512 };
addPropertyControls(FramerOTPOYii8D, {
  variant: {
    options: ["y__q1nPZj", "P5CagX797", "BQJw3dP9_", "YdeR8Bh5K"],
    optionTitles: ["Variant 1", "Variant 2", "Variant 3", "Variant 4"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerOTPOYii8D,
  [
    { explicitInter: true, fonts: [] },
    ...Phase1Fonts,
    ...Phase2Fonts,
    ...Phase3Fonts,
    ...Phase4Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerOTPOYii8D",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "1512",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"P5CagX797":{"layout":["fixed","auto"]},"BQJw3dP9_":{"layout":["fixed","auto"]},"YdeR8Bh5K":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "881",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./OTPOYii8D.map
